package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEducation <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */
public class DefaultEducation extends WrappedIndividualImpl implements Education {

    public DefaultEducation(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasSchoolAttended
     */
     
    public Collection<? extends SchoolAttended> getHasSchoolAttended() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSCHOOLATTENDED,
                                               DefaultSchoolAttended.class);
    }

    public boolean hasHasSchoolAttended() {
	   return !getHasSchoolAttended().isEmpty();
    }

    public void addHasSchoolAttended(SchoolAttended newHasSchoolAttended) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSCHOOLATTENDED,
                                       newHasSchoolAttended);
    }

    public void removeHasSchoolAttended(SchoolAttended oldHasSchoolAttended) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSCHOOLATTENDED,
                                          oldHasSchoolAttended);
    }


    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasTakenCourse
     */
     
    public Collection<? extends Course> getHasTakenCourse() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASTAKENCOURSE,
                                               DefaultCourse.class);
    }

    public boolean hasHasTakenCourse() {
	   return !getHasTakenCourse().isEmpty();
    }

    public void addHasTakenCourse(Course newHasTakenCourse) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASTAKENCOURSE,
                                       newHasTakenCourse);
    }

    public void removeHasTakenCourse(Course oldHasTakenCourse) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASTAKENCOURSE,
                                          oldHasTakenCourse);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasHigestLevelOfAquiredEducation
     */
     
    public Collection<? extends Object> getHasHigestLevelOfAquiredEducation() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHIGESTLEVELOFAQUIREDEDUCATION, Object.class);
    }

    public boolean hasHasHigestLevelOfAquiredEducation() {
		return !getHasHigestLevelOfAquiredEducation().isEmpty();
    }

    public void addHasHigestLevelOfAquiredEducation(Object newHasHigestLevelOfAquiredEducation) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHIGESTLEVELOFAQUIREDEDUCATION, newHasHigestLevelOfAquiredEducation);
    }

    public void removeHasHigestLevelOfAquiredEducation(Object oldHasHigestLevelOfAquiredEducation) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHIGESTLEVELOFAQUIREDEDUCATION, oldHasHigestLevelOfAquiredEducation);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasKeyTags
     */
     
    public Collection<? extends String> getHasKeyTags() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASKEYTAGS, String.class);
    }

    public boolean hasHasKeyTags() {
		return !getHasKeyTags().isEmpty();
    }

    public void addHasKeyTags(String newHasKeyTags) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASKEYTAGS, newHasKeyTags);
    }

    public void removeHasKeyTags(String oldHasKeyTags) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASKEYTAGS, oldHasKeyTags);
    }


}
