package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLanguageDetails <br>
 * @version generated on Fri May 23 10:57:54 CEST 2014 by cknguyen
 */
public class DefaultLanguageDetails extends WrappedIndividualImpl implements LanguageDetails {

    public DefaultLanguageDetails(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasLanguageName
     */
     
    public Collection<? extends String> getHasLanguageName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLANGUAGENAME, String.class);
    }

    public boolean hasHasLanguageName() {
		return !getHasLanguageName().isEmpty();
    }

    public void addHasLanguageName(String newHasLanguageName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLANGUAGENAME, newHasLanguageName);
    }

    public void removeHasLanguageName(String oldHasLanguageName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLANGUAGENAME, oldHasLanguageName);
    }


}
