package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEventPreference <br>
 * @version generated on Fri May 23 10:57:54 CEST 2014 by cknguyen
 */
public class DefaultEventPreference extends WrappedIndividualImpl implements EventPreference {

    public DefaultEventPreference(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasEventDetailPreference
     */
     
    public Collection<? extends EventDetailPreference> getHasEventDetailPreference() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASEVENTDETAILPREFERENCE,
                                               DefaultEventDetailPreference.class);
    }

    public boolean hasHasEventDetailPreference() {
	   return !getHasEventDetailPreference().isEmpty();
    }

    public void addHasEventDetailPreference(EventDetailPreference newHasEventDetailPreference) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASEVENTDETAILPREFERENCE,
                                       newHasEventDetailPreference);
    }

    public void removeHasEventDetailPreference(EventDetailPreference oldHasEventDetailPreference) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASEVENTDETAILPREFERENCE,
                                          oldHasEventDetailPreference);
    }


    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasEventRatingPreference
     */
     
    public Collection<? extends RatingPreference> getHasEventRatingPreference() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASEVENTRATINGPREFERENCE,
                                               DefaultRatingPreference.class);
    }

    public boolean hasHasEventRatingPreference() {
	   return !getHasEventRatingPreference().isEmpty();
    }

    public void addHasEventRatingPreference(RatingPreference newHasEventRatingPreference) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASEVENTRATINGPREFERENCE,
                                       newHasEventRatingPreference);
    }

    public void removeHasEventRatingPreference(RatingPreference oldHasEventRatingPreference) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASEVENTRATINGPREFERENCE,
                                          oldHasEventRatingPreference);
    }


}
