package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEmployer <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */
public class DefaultEmployer extends WrappedIndividualImpl implements Employer {

    public DefaultEmployer(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.w3.org/2006/vcard/ns#hasAddress
     */
     
    public Collection<? extends WrappedIndividual> getHas_address() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_ADDRESS,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHas_address() {
	   return !getHas_address().isEmpty();
    }

    public void addHas_address(WrappedIndividual newHas_address) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_ADDRESS,
                                       newHas_address);
    }

    public void removeHas_address(WrappedIndividual oldHas_address) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_ADDRESS,
                                          oldHas_address);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasDetail
     */
     
    public Collection<? extends String> getHasDetail() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDETAIL, String.class);
    }

    public boolean hasHasDetail() {
		return !getHasDetail().isEmpty();
    }

    public void addHasDetail(String newHasDetail) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDETAIL, newHasDetail);
    }

    public void removeHasDetail(String oldHasDetail) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDETAIL, oldHasDetail);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasEmployerName
     */
     
    public Collection<? extends String> getHasEmployerName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMPLOYERNAME, String.class);
    }

    public boolean hasHasEmployerName() {
		return !getHasEmployerName().isEmpty();
    }

    public void addHasEmployerName(String newHasEmployerName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMPLOYERNAME, newHasEmployerName);
    }

    public void removeHasEmployerName(String oldHasEmployerName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEMPLOYERNAME, oldHasEmployerName);
    }


}
