package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultQueryHistory <br>
 * @version generated on Fri May 23 10:57:54 CEST 2014 by cknguyen
 */
public class DefaultQueryHistory extends WrappedIndividualImpl implements QueryHistory {

    public DefaultQueryHistory(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasQueryTime
     */
     
    public Collection<? extends Object> getHasQueryTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASQUERYTIME, Object.class);
    }

    public boolean hasHasQueryTime() {
		return !getHasQueryTime().isEmpty();
    }

    public void addHasQueryTime(Object newHasQueryTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASQUERYTIME, newHasQueryTime);
    }

    public void removeHasQueryTime(Object oldHasQueryTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASQUERYTIME, oldHasQueryTime);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasUID
     */
     
    public Collection<? extends String> getHasUID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUID, String.class);
    }

    public boolean hasHasUID() {
		return !getHasUID().isEmpty();
    }

    public void addHasUID(String newHasUID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUID, newHasUID);
    }

    public void removeHasUID(String oldHasUID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUID, oldHasUID);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#query
     */
     
    public Collection<? extends String> getQuery() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_QUERY, String.class);
    }

    public boolean hasQuery() {
		return !getQuery().isEmpty();
    }

    public void addQuery(String newQuery) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_QUERY, newQuery);
    }

    public void removeQuery(String oldQuery) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_QUERY, oldQuery);
    }


}
