package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTray <br>
 * @version generated on Wed Jun 25 09:55:40 CEST 2014 by ragarwal
 */
public class DefaultTray extends WrappedIndividualImpl implements Tray {

    public DefaultTray(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#attended
     */
     
    public Collection<? extends Boolean> getAttended() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATTENDED, Boolean.class);
    }

    public boolean hasAttended() {
		return !getAttended().isEmpty();
    }

    public void addAttended(Boolean newAttended) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATTENDED, newAttended);
    }

    public void removeAttended(Boolean oldAttended) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATTENDED, oldAttended);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#dateTimeAttended
     */
     
    public Collection<? extends Long> getDateTimeAttended() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATETIMEATTENDED, Long.class);
    }

    public boolean hasDateTimeAttended() {
		return !getDateTimeAttended().isEmpty();
    }

    public void addDateTimeAttended(Long newDateTimeAttended) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATETIMEATTENDED, newDateTimeAttended);
    }

    public void removeDateTimeAttended(Long oldDateTimeAttended) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATETIMEATTENDED, oldDateTimeAttended);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasSource
     */
     
    public Collection<? extends String> getHasSource() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSOURCE, String.class);
    }

    public boolean hasHasSource() {
		return !getHasSource().isEmpty();
    }

    public void addHasSource(String newHasSource) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSOURCE, newHasSource);
    }

    public void removeHasSource(String oldHasSource) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSOURCE, oldHasSource);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasUID
     */
     
    public Collection<? extends String> getHasUID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUID, String.class);
    }

    public boolean hasHasUID() {
		return !getHasUID().isEmpty();
    }

    public void addHasUID(String newHasUID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUID, newHasUID);
    }

    public void removeHasUID(String oldHasUID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUID, oldHasUID);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasUserDefinedRating
     */
     
    public Collection<? extends Object> getHasUserDefinedRating() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERDEFINEDRATING, Object.class);
    }

    public boolean hasHasUserDefinedRating() {
		return !getHasUserDefinedRating().isEmpty();
    }

    public void addHasUserDefinedRating(Object newHasUserDefinedRating) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERDEFINEDRATING, newHasUserDefinedRating);
    }

    public void removeHasUserDefinedRating(Object oldHasUserDefinedRating) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERDEFINEDRATING, oldHasUserDefinedRating);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#itemID
     */
     
    public Collection<? extends String> getItemID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ITEMID, String.class);
    }

    public boolean hasItemID() {
		return !getItemID().isEmpty();
    }

    public void addItemID(String newItemID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ITEMID, newItemID);
    }

    public void removeItemID(String oldItemID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ITEMID, oldItemID);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#itemType
     */
     
    public Collection<? extends Object> getItemType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ITEMTYPE, Object.class);
    }

    public boolean hasItemType() {
		return !getItemType().isEmpty();
    }

    public void addItemType(Object newItemType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ITEMTYPE, newItemType);
    }

    public void removeItemType(Object oldItemType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ITEMTYPE, oldItemType);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#timestamp
     */
     
    public Collection<? extends Long> getTimestamp() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TIMESTAMP, Long.class);
    }

    public boolean hasTimestamp() {
		return !getTimestamp().isEmpty();
    }

    public void addTimestamp(Long newTimestamp) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TIMESTAMP, newTimestamp);
    }

    public void removeTimestamp(Long oldTimestamp) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TIMESTAMP, oldTimestamp);
    }


}
