package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultModalityStatistics <br>
 * @version generated on Fri May 23 10:57:54 CEST 2014 by cknguyen
 */
public class DefaultModalityStatistics extends WrappedIndividualImpl implements ModalityStatistics {

    public DefaultModalityStatistics(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAverageSpeed
     */
     
    public Collection<? extends Object> getHasAverageSpeed() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASAVERAGESPEED, Object.class);
    }

    public boolean hasHasAverageSpeed() {
		return !getHasAverageSpeed().isEmpty();
    }

    public void addHasAverageSpeed(Object newHasAverageSpeed) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASAVERAGESPEED, newHasAverageSpeed);
    }

    public void removeHasAverageSpeed(Object oldHasAverageSpeed) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASAVERAGESPEED, oldHasAverageSpeed);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasInRushHour
     */
     
    public Collection<? extends Boolean> getHasInRushHour() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASINRUSHHOUR, Boolean.class);
    }

    public boolean hasHasInRushHour() {
		return !getHasInRushHour().isEmpty();
    }

    public void addHasInRushHour(Boolean newHasInRushHour) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASINRUSHHOUR, newHasInRushHour);
    }

    public void removeHasInRushHour(Boolean oldHasInRushHour) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASINRUSHHOUR, oldHasInRushHour);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasModalityType
     */
     
    public Collection<? extends Object> getHasModalityType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMODALITYTYPE, Object.class);
    }

    public boolean hasHasModalityType() {
		return !getHasModalityType().isEmpty();
    }

    public void addHasModalityType(Object newHasModalityType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMODALITYTYPE, newHasModalityType);
    }

    public void removeHasModalityType(Object oldHasModalityType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMODALITYTYPE, oldHasModalityType);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasOriginDestinationPair
     */
     
    public Collection<? extends String> getHasOriginDestinationPair() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASORIGINDESTINATIONPAIR, String.class);
    }

    public boolean hasHasOriginDestinationPair() {
		return !getHasOriginDestinationPair().isEmpty();
    }

    public void addHasOriginDestinationPair(String newHasOriginDestinationPair) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASORIGINDESTINATIONPAIR, newHasOriginDestinationPair);
    }

    public void removeHasOriginDestinationPair(String oldHasOriginDestinationPair) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASORIGINDESTINATIONPAIR, oldHasOriginDestinationPair);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasTotalCalories
     */
     
    public Collection<? extends Object> getHasTotalCalories() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCALORIES, Object.class);
    }

    public boolean hasHasTotalCalories() {
		return !getHasTotalCalories().isEmpty();
    }

    public void addHasTotalCalories(Object newHasTotalCalories) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCALORIES, newHasTotalCalories);
    }

    public void removeHasTotalCalories(Object oldHasTotalCalories) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCALORIES, oldHasTotalCalories);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasTotalCost
     */
     
    public Collection<? extends Object> getHasTotalCost() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCOST, Object.class);
    }

    public boolean hasHasTotalCost() {
		return !getHasTotalCost().isEmpty();
    }

    public void addHasTotalCost(Object newHasTotalCost) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCOST, newHasTotalCost);
    }

    public void removeHasTotalCost(Object oldHasTotalCost) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCOST, oldHasTotalCost);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasTotalCount
     */
     
    public Collection<? extends Long> getHasTotalCount() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCOUNT, Long.class);
    }

    public boolean hasHasTotalCount() {
		return !getHasTotalCount().isEmpty();
    }

    public void addHasTotalCount(Long newHasTotalCount) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCOUNT, newHasTotalCount);
    }

    public void removeHasTotalCount(Long oldHasTotalCount) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALCOUNT, oldHasTotalCount);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasTotalDistance
     */
     
    public Collection<? extends Object> getHasTotalDistance() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALDISTANCE, Object.class);
    }

    public boolean hasHasTotalDistance() {
		return !getHasTotalDistance().isEmpty();
    }

    public void addHasTotalDistance(Object newHasTotalDistance) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALDISTANCE, newHasTotalDistance);
    }

    public void removeHasTotalDistance(Object oldHasTotalDistance) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALDISTANCE, oldHasTotalDistance);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasTotalLostTime
     */
     
    public Collection<? extends Long> getHasTotalLostTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALLOSTTIME, Long.class);
    }

    public boolean hasHasTotalLostTime() {
		return !getHasTotalLostTime().isEmpty();
    }

    public void addHasTotalLostTime(Long newHasTotalLostTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALLOSTTIME, newHasTotalLostTime);
    }

    public void removeHasTotalLostTime(Long oldHasTotalLostTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALLOSTTIME, oldHasTotalLostTime);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasTotalTime
     */
     
    public Collection<? extends Long> getHasTotalTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALTIME, Long.class);
    }

    public boolean hasHasTotalTime() {
		return !getHasTotalTime().isEmpty();
    }

    public void addHasTotalTime(Long newHasTotalTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALTIME, newHasTotalTime);
    }

    public void removeHasTotalTime(Long oldHasTotalTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTOTALTIME, oldHasTotalTime);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasTravelObjectiveType
     */
     
    public Collection<? extends Object> getHasTravelObjectiveType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAVELOBJECTIVETYPE, Object.class);
    }

    public boolean hasHasTravelObjectiveType() {
		return !getHasTravelObjectiveType().isEmpty();
    }

    public void addHasTravelObjectiveType(Object newHasTravelObjectiveType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAVELOBJECTIVETYPE, newHasTravelObjectiveType);
    }

    public void removeHasTravelObjectiveType(Object oldHasTravelObjectiveType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAVELOBJECTIVETYPE, oldHasTravelObjectiveType);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasWeatherConditions
     */
     
    public Collection<? extends String> getHasWeatherConditions() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHERCONDITIONS, String.class);
    }

    public boolean hasHasWeatherConditions() {
		return !getHasWeatherConditions().isEmpty();
    }

    public void addHasWeatherConditions(String newHasWeatherConditions) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHERCONDITIONS, newHasWeatherConditions);
    }

    public void removeHasWeatherConditions(String oldHasWeatherConditions) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHERCONDITIONS, oldHasWeatherConditions);
    }


}
