package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPlaceDetailPreference <br>
 * @version generated on Mon Jun 02 16:02:21 CEST 2014 by ragarwal
 */
public class DefaultPlaceDetailPreference extends WrappedIndividualImpl implements PlaceDetailPreference {

    public DefaultPlaceDetailPreference(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasPreferredApproximateAddress
     */
     
    public Collection<? extends Address> getHasPreferredApproximateAddress() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASPREFERREDAPPROXIMATEADDRESS,
                                               DefaultAddress.class);
    }

    public boolean hasHasPreferredApproximateAddress() {
	   return !getHasPreferredApproximateAddress().isEmpty();
    }

    public void addHasPreferredApproximateAddress(Address newHasPreferredApproximateAddress) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASPREFERREDAPPROXIMATEADDRESS,
                                       newHasPreferredApproximateAddress);
    }

    public void removeHasPreferredApproximateAddress(Address oldHasPreferredApproximateAddress) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASPREFERREDAPPROXIMATEADDRESS,
                                          oldHasPreferredApproximateAddress);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasNatureOfPlace
     */
     
    public Collection<? extends Object> getHasNatureOfPlace() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFPLACE, Object.class);
    }

    public boolean hasHasNatureOfPlace() {
		return !getHasNatureOfPlace().isEmpty();
    }

    public void addHasNatureOfPlace(Object newHasNatureOfPlace) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFPLACE, newHasNatureOfPlace);
    }

    public void removeHasNatureOfPlace(Object oldHasNatureOfPlace) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFPLACE, oldHasNatureOfPlace);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasPreferredPlaceKeyTags
     */
     
    public Collection<? extends String> getHasPreferredPlaceKeyTags() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASPREFERREDPLACEKEYTAGS, String.class);
    }

    public boolean hasHasPreferredPlaceKeyTags() {
		return !getHasPreferredPlaceKeyTags().isEmpty();
    }

    public void addHasPreferredPlaceKeyTags(String newHasPreferredPlaceKeyTags) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASPREFERREDPLACEKEYTAGS, newHasPreferredPlaceKeyTags);
    }

    public void removeHasPreferredPlaceKeyTags(String oldHasPreferredPlaceKeyTags) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASPREFERREDPLACEKEYTAGS, oldHasPreferredPlaceKeyTags);
    }


}
