package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAccompanying <br>
 * @version generated on Fri May 23 10:57:54 CEST 2014 by cknguyen
 */
public class DefaultAccompanying extends WrappedIndividualImpl implements Accompanying {

    public DefaultAccompanying(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasAccompanyTrip1
     */
     
    public Collection<? extends TripMeasurement> getHasAccompanyTrip1() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASACCOMPANYTRIP1,
                                               DefaultTripMeasurement.class);
    }

    public boolean hasHasAccompanyTrip1() {
	   return !getHasAccompanyTrip1().isEmpty();
    }

    public void addHasAccompanyTrip1(TripMeasurement newHasAccompanyTrip1) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASACCOMPANYTRIP1,
                                       newHasAccompanyTrip1);
    }

    public void removeHasAccompanyTrip1(TripMeasurement oldHasAccompanyTrip1) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASACCOMPANYTRIP1,
                                          oldHasAccompanyTrip1);
    }


    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasAccompanyTrip2
     */
     
    public Collection<? extends TripMeasurement> getHasAccompanyTrip2() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASACCOMPANYTRIP2,
                                               DefaultTripMeasurement.class);
    }

    public boolean hasHasAccompanyTrip2() {
	   return !getHasAccompanyTrip2().isEmpty();
    }

    public void addHasAccompanyTrip2(TripMeasurement newHasAccompanyTrip2) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASACCOMPANYTRIP2,
                                       newHasAccompanyTrip2);
    }

    public void removeHasAccompanyTrip2(TripMeasurement oldHasAccompanyTrip2) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASACCOMPANYTRIP2,
                                          oldHasAccompanyTrip2);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyDomainName
     */
     
    public Collection<? extends String> getHasAccompanyDomainName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYDOMAINNAME, String.class);
    }

    public boolean hasHasAccompanyDomainName() {
		return !getHasAccompanyDomainName().isEmpty();
    }

    public void addHasAccompanyDomainName(String newHasAccompanyDomainName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYDOMAINNAME, newHasAccompanyDomainName);
    }

    public void removeHasAccompanyDomainName(String oldHasAccompanyDomainName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYDOMAINNAME, oldHasAccompanyDomainName);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyID
     */
     
    public Collection<? extends Long> getHasAccompanyID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYID, Long.class);
    }

    public boolean hasHasAccompanyID() {
		return !getHasAccompanyID().isEmpty();
    }

    public void addHasAccompanyID(Long newHasAccompanyID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYID, newHasAccompanyID);
    }

    public void removeHasAccompanyID(Long oldHasAccompanyID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYID, oldHasAccompanyID);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyScore
     */
     
    public Collection<? extends Object> getHasAccompanyScore() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYSCORE, Object.class);
    }

    public boolean hasHasAccompanyScore() {
		return !getHasAccompanyScore().isEmpty();
    }

    public void addHasAccompanyScore(Object newHasAccompanyScore) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYSCORE, newHasAccompanyScore);
    }

    public void removeHasAccompanyScore(Object oldHasAccompanyScore) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYSCORE, oldHasAccompanyScore);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyTime
     */
     
    public Collection<? extends Long> getHasAccompanyTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYTIME, Long.class);
    }

    public boolean hasHasAccompanyTime() {
		return !getHasAccompanyTime().isEmpty();
    }

    public void addHasAccompanyTime(Long newHasAccompanyTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYTIME, newHasAccompanyTime);
    }

    public void removeHasAccompanyTime(Long oldHasAccompanyTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYTIME, oldHasAccompanyTime);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyTimeZone
     */
     
    public Collection<? extends Long> getHasAccompanyTimeZone() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYTIMEZONE, Long.class);
    }

    public boolean hasHasAccompanyTimeZone() {
		return !getHasAccompanyTimeZone().isEmpty();
    }

    public void addHasAccompanyTimeZone(Long newHasAccompanyTimeZone) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYTIMEZONE, newHasAccompanyTimeZone);
    }

    public void removeHasAccompanyTimeZone(Long oldHasAccompanyTimeZone) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYTIMEZONE, oldHasAccompanyTimeZone);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyUserID1
     */
     
    public Collection<? extends Long> getHasAccompanyUserID1() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYUSERID1, Long.class);
    }

    public boolean hasHasAccompanyUserID1() {
		return !getHasAccompanyUserID1().isEmpty();
    }

    public void addHasAccompanyUserID1(Long newHasAccompanyUserID1) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYUSERID1, newHasAccompanyUserID1);
    }

    public void removeHasAccompanyUserID1(Long oldHasAccompanyUserID1) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYUSERID1, oldHasAccompanyUserID1);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyUserID2
     */
     
    public Collection<? extends Long> getHasAccompanyUserID2() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYUSERID2, Long.class);
    }

    public boolean hasHasAccompanyUserID2() {
		return !getHasAccompanyUserID2().isEmpty();
    }

    public void addHasAccompanyUserID2(Long newHasAccompanyUserID2) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYUSERID2, newHasAccompanyUserID2);
    }

    public void removeHasAccompanyUserID2(Long oldHasAccompanyUserID2) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYUSERID2, oldHasAccompanyUserID2);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasAccompanyValidity
     */
     
    public Collection<? extends Long> getHasAccompanyValidity() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYVALIDITY, Long.class);
    }

    public boolean hasHasAccompanyValidity() {
		return !getHasAccompanyValidity().isEmpty();
    }

    public void addHasAccompanyValidity(Long newHasAccompanyValidity) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYVALIDITY, newHasAccompanyValidity);
    }

    public void removeHasAccompanyValidity(Long oldHasAccompanyValidity) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASACCOMPANYVALIDITY, oldHasAccompanyValidity);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasDecisionLevel
     */
     
    public Collection<? extends Object> getHasDecisionLevel() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDECISIONLEVEL, Object.class);
    }

    public boolean hasHasDecisionLevel() {
		return !getHasDecisionLevel().isEmpty();
    }

    public void addHasDecisionLevel(Object newHasDecisionLevel) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDECISIONLEVEL, newHasDecisionLevel);
    }

    public void removeHasDecisionLevel(Object oldHasDecisionLevel) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDECISIONLEVEL, oldHasDecisionLevel);
    }


}
