package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultRating <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */
public class DefaultRating extends WrappedIndividualImpl implements Rating {

    public DefaultRating(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasKeyTags
     */
     
    public Collection<? extends String> getHasKeyTags() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASKEYTAGS, String.class);
    }

    public boolean hasHasKeyTags() {
		return !getHasKeyTags().isEmpty();
    }

    public void addHasKeyTags(String newHasKeyTags) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASKEYTAGS, newHasKeyTags);
    }

    public void removeHasKeyTags(String oldHasKeyTags) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASKEYTAGS, oldHasKeyTags);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasUserDefinedRating
     */
     
    public Collection<? extends Object> getHasUserDefinedRating() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERDEFINEDRATING, Object.class);
    }

    public boolean hasHasUserDefinedRating() {
		return !getHasUserDefinedRating().isEmpty();
    }

    public void addHasUserDefinedRating(Object newHasUserDefinedRating) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERDEFINEDRATING, newHasUserDefinedRating);
    }

    public void removeHasUserDefinedRating(Object oldHasUserDefinedRating) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERDEFINEDRATING, oldHasUserDefinedRating);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasUserInteractionMode
     */
     
    public Collection<? extends Object> getHasUserInteractionMode() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERINTERACTIONMODE, Object.class);
    }

    public boolean hasHasUserInteractionMode() {
		return !getHasUserInteractionMode().isEmpty();
    }

    public void addHasUserInteractionMode(Object newHasUserInteractionMode) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERINTERACTIONMODE, newHasUserInteractionMode);
    }

    public void removeHasUserInteractionMode(Object oldHasUserInteractionMode) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUSERINTERACTIONMODE, oldHasUserInteractionMode);
    }


}
