package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEmployerInformation <br>
 * @version generated on Wed Jun 25 09:55:40 CEST 2014 by ragarwal
 */
public class DefaultEmployerInformation extends WrappedIndividualImpl implements EmployerInformation {

    public DefaultEmployerInformation(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://linkedevents.org/ontology/atPlace
     */
     
    public Collection<? extends Address> getAt_place() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AT_PLACE,
                                               DefaultAddress.class);
    }

    public boolean hasAt_place() {
	   return !getAt_place().isEmpty();
    }

    public void addAt_place(Address newAt_place) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AT_PLACE,
                                       newAt_place);
    }

    public void removeAt_place(Address oldAt_place) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AT_PLACE,
                                          oldAt_place);
    }


    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasEmployer
     */
     
    public Collection<? extends Employer> getHasEmployer() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASEMPLOYER,
                                               DefaultEmployer.class);
    }

    public boolean hasHasEmployer() {
	   return !getHasEmployer().isEmpty();
    }

    public void addHasEmployer(Employer newHasEmployer) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASEMPLOYER,
                                       newHasEmployer);
    }

    public void removeHasEmployer(Employer oldHasEmployer) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASEMPLOYER,
                                          oldHasEmployer);
    }


    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasTemporalDetails
     */
     
    public Collection<? extends TemporalDetails> getHasTemporalDetails() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASTEMPORALDETAILS,
                                               DefaultTemporalDetails.class);
    }

    public boolean hasHasTemporalDetails() {
	   return !getHasTemporalDetails().isEmpty();
    }

    public void addHasTemporalDetails(TemporalDetails newHasTemporalDetails) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASTEMPORALDETAILS,
                                       newHasTemporalDetails);
    }

    public void removeHasTemporalDetails(TemporalDetails oldHasTemporalDetails) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASTEMPORALDETAILS,
                                          oldHasTemporalDetails);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasEventName
     */
     
    public Collection<? extends Object> getHasEventName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEVENTNAME, Object.class);
    }

    public boolean hasHasEventName() {
		return !getHasEventName().isEmpty();
    }

    public void addHasEventName(Object newHasEventName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEVENTNAME, newHasEventName);
    }

    public void removeHasEventName(Object oldHasEventName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEVENTNAME, oldHasEventName);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasNatureOfEvent
     */
     
    public Collection<? extends Object> getHasNatureOfEvent() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFEVENT, Object.class);
    }

    public boolean hasHasNatureOfEvent() {
		return !getHasNatureOfEvent().isEmpty();
    }

    public void addHasNatureOfEvent(Object newHasNatureOfEvent) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFEVENT, newHasNatureOfEvent);
    }

    public void removeHasNatureOfEvent(Object oldHasNatureOfEvent) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFEVENT, oldHasNatureOfEvent);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasNatureOfWork
     */
     
    public Collection<? extends Object> getHasNatureOfWork() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFWORK, Object.class);
    }

    public boolean hasHasNatureOfWork() {
		return !getHasNatureOfWork().isEmpty();
    }

    public void addHasNatureOfWork(Object newHasNatureOfWork) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFWORK, newHasNatureOfWork);
    }

    public void removeHasNatureOfWork(Object oldHasNatureOfWork) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASNATUREOFWORK, oldHasNatureOfWork);
    }


}
