package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAddress <br>
 * @version generated on Wed Jun 25 09:55:40 CEST 2014 by ragarwal
 */
public class DefaultAddress extends WrappedIndividualImpl implements Address {

    public DefaultAddress(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#townName
     */
     
    public Collection<? extends Object> getTownName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOWNNAME, Object.class);
    }

    public boolean hasTownName() {
		return !getTownName().isEmpty();
    }

    public void addTownName(Object newTownName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOWNNAME, newTownName);
    }

    public void removeTownName(Object oldTownName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOWNNAME, oldTownName);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#country-name
     */
     
    public Collection<? extends Object> getCountry_name() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRY_NAME, Object.class);
    }

    public boolean hasCountry_name() {
		return !getCountry_name().isEmpty();
    }

    public void addCountry_name(Object newCountry_name) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRY_NAME, newCountry_name);
    }

    public void removeCountry_name(Object oldCountry_name) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRY_NAME, oldCountry_name);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#latitude
     */
     
    public Collection<? extends Object> getLatitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LATITUDE, Object.class);
    }

    public boolean hasLatitude() {
		return !getLatitude().isEmpty();
    }

    public void addLatitude(Object newLatitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LATITUDE, newLatitude);
    }

    public void removeLatitude(Object oldLatitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LATITUDE, oldLatitude);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#longitude
     */
     
    public Collection<? extends Object> getLongitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LONGITUDE, Object.class);
    }

    public boolean hasLongitude() {
		return !getLongitude().isEmpty();
    }

    public void addLongitude(Object newLongitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LONGITUDE, newLongitude);
    }

    public void removeLongitude(Object oldLongitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LONGITUDE, oldLongitude);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#post-office-box
     */
     
    public Collection<? extends String> getPost_office_box() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POST_OFFICE_BOX, String.class);
    }

    public boolean hasPost_office_box() {
		return !getPost_office_box().isEmpty();
    }

    public void addPost_office_box(String newPost_office_box) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POST_OFFICE_BOX, newPost_office_box);
    }

    public void removePost_office_box(String oldPost_office_box) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POST_OFFICE_BOX, oldPost_office_box);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#postal-code
     */
     
    public Collection<? extends Object> getPostal_code() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POSTAL_CODE, Object.class);
    }

    public boolean hasPostal_code() {
		return !getPostal_code().isEmpty();
    }

    public void addPostal_code(Object newPostal_code) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POSTAL_CODE, newPostal_code);
    }

    public void removePostal_code(Object oldPostal_code) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POSTAL_CODE, oldPostal_code);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#street-address
     */
     
    public Collection<? extends Object> getStreet_address() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STREET_ADDRESS, Object.class);
    }

    public boolean hasStreet_address() {
		return !getStreet_address().isEmpty();
    }

    public void addStreet_address(Object newStreet_address) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STREET_ADDRESS, newStreet_address);
    }

    public void removeStreet_address(Object oldStreet_address) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STREET_ADDRESS, oldStreet_address);
    }


}
