package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultSocialPreference <br>
 * @version generated on Fri May 23 10:57:54 CEST 2014 by cknguyen
 */
public class DefaultSocialPreference extends WrappedIndividualImpl implements SocialPreference {

    public DefaultSocialPreference(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.eu.3cixty.org/profile#hasAccompany
     */
     
    public Collection<? extends Accompanying> getHasAccompany() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASACCOMPANY,
                                               DefaultAccompanying.class);
    }

    public boolean hasHasAccompany() {
	   return !getHasAccompany().isEmpty();
    }

    public void addHasAccompany(Accompanying newHasAccompany) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASACCOMPANY,
                                       newHasAccompany);
    }

    public void removeHasAccompany(Accompanying oldHasAccompany) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASACCOMPANY,
                                          oldHasAccompany);
    }


}
