package eu.threecixty.models.impl;

import eu.threecixty.models.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMappedLocation <br>
 * @version generated on Wed Jun 25 09:55:40 CEST 2014 by ragarwal
 */
public class DefaultMappedLocation extends WrappedIndividualImpl implements MappedLocation {

    public DefaultMappedLocation(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationAerialway
     */
     
    public Collection<? extends String> getHasMappedLocationAerialway() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONAERIALWAY, String.class);
    }

    public boolean hasHasMappedLocationAerialway() {
		return !getHasMappedLocationAerialway().isEmpty();
    }

    public void addHasMappedLocationAerialway(String newHasMappedLocationAerialway) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONAERIALWAY, newHasMappedLocationAerialway);
    }

    public void removeHasMappedLocationAerialway(String oldHasMappedLocationAerialway) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONAERIALWAY, oldHasMappedLocationAerialway);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationDeviation
     */
     
    public Collection<? extends String> getHasMappedLocationDeviation() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONDEVIATION, String.class);
    }

    public boolean hasHasMappedLocationDeviation() {
		return !getHasMappedLocationDeviation().isEmpty();
    }

    public void addHasMappedLocationDeviation(String newHasMappedLocationDeviation) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONDEVIATION, newHasMappedLocationDeviation);
    }

    public void removeHasMappedLocationDeviation(String oldHasMappedLocationDeviation) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONDEVIATION, oldHasMappedLocationDeviation);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationDistance
     */
     
    public Collection<? extends Object> getHasMappedLocationDistance() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONDISTANCE, Object.class);
    }

    public boolean hasHasMappedLocationDistance() {
		return !getHasMappedLocationDistance().isEmpty();
    }

    public void addHasMappedLocationDistance(Object newHasMappedLocationDistance) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONDISTANCE, newHasMappedLocationDistance);
    }

    public void removeHasMappedLocationDistance(Object oldHasMappedLocationDistance) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONDISTANCE, oldHasMappedLocationDistance);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationHighway
     */
     
    public Collection<? extends String> getHasMappedLocationHighway() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONHIGHWAY, String.class);
    }

    public boolean hasHasMappedLocationHighway() {
		return !getHasMappedLocationHighway().isEmpty();
    }

    public void addHasMappedLocationHighway(String newHasMappedLocationHighway) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONHIGHWAY, newHasMappedLocationHighway);
    }

    public void removeHasMappedLocationHighway(String oldHasMappedLocationHighway) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONHIGHWAY, oldHasMappedLocationHighway);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationID
     */
     
    public Collection<? extends Long> getHasMappedLocationID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONID, Long.class);
    }

    public boolean hasHasMappedLocationID() {
		return !getHasMappedLocationID().isEmpty();
    }

    public void addHasMappedLocationID(Long newHasMappedLocationID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONID, newHasMappedLocationID);
    }

    public void removeHasMappedLocationID(Long oldHasMappedLocationID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONID, oldHasMappedLocationID);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationName
     */
     
    public Collection<? extends String> getHasMappedLocationName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONNAME, String.class);
    }

    public boolean hasHasMappedLocationName() {
		return !getHasMappedLocationName().isEmpty();
    }

    public void addHasMappedLocationName(String newHasMappedLocationName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONNAME, newHasMappedLocationName);
    }

    public void removeHasMappedLocationName(String oldHasMappedLocationName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONNAME, oldHasMappedLocationName);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationNodeID
     */
     
    public Collection<? extends Long> getHasMappedLocationNodeID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONNODEID, Long.class);
    }

    public boolean hasHasMappedLocationNodeID() {
		return !getHasMappedLocationNodeID().isEmpty();
    }

    public void addHasMappedLocationNodeID(Long newHasMappedLocationNodeID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONNODEID, newHasMappedLocationNodeID);
    }

    public void removeHasMappedLocationNodeID(Long oldHasMappedLocationNodeID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONNODEID, oldHasMappedLocationNodeID);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationRailway
     */
     
    public Collection<? extends String> getHasMappedLocationRailway() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONRAILWAY, String.class);
    }

    public boolean hasHasMappedLocationRailway() {
		return !getHasMappedLocationRailway().isEmpty();
    }

    public void addHasMappedLocationRailway(String newHasMappedLocationRailway) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONRAILWAY, newHasMappedLocationRailway);
    }

    public void removeHasMappedLocationRailway(String oldHasMappedLocationRailway) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONRAILWAY, oldHasMappedLocationRailway);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationServiceRoadway
     */
     
    public Collection<? extends String> getHasMappedLocationServiceRoadway() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONSERVICEROADWAY, String.class);
    }

    public boolean hasHasMappedLocationServiceRoadway() {
		return !getHasMappedLocationServiceRoadway().isEmpty();
    }

    public void addHasMappedLocationServiceRoadway(String newHasMappedLocationServiceRoadway) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONSERVICEROADWAY, newHasMappedLocationServiceRoadway);
    }

    public void removeHasMappedLocationServiceRoadway(String oldHasMappedLocationServiceRoadway) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONSERVICEROADWAY, oldHasMappedLocationServiceRoadway);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationTime
     */
     
    public Collection<? extends Object> getHasMappedLocationTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONTIME, Object.class);
    }

    public boolean hasHasMappedLocationTime() {
		return !getHasMappedLocationTime().isEmpty();
    }

    public void addHasMappedLocationTime(Object newHasMappedLocationTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONTIME, newHasMappedLocationTime);
    }

    public void removeHasMappedLocationTime(Object oldHasMappedLocationTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONTIME, oldHasMappedLocationTime);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationWaterway
     */
     
    public Collection<? extends String> getHasMappedLocationWaterway() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONWATERWAY, String.class);
    }

    public boolean hasHasMappedLocationWaterway() {
		return !getHasMappedLocationWaterway().isEmpty();
    }

    public void addHasMappedLocationWaterway(String newHasMappedLocationWaterway) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONWATERWAY, newHasMappedLocationWaterway);
    }

    public void removeHasMappedLocationWaterway(String oldHasMappedLocationWaterway) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONWATERWAY, oldHasMappedLocationWaterway);
    }


    /* ***************************************************
     * Data Property http://www.eu.3cixty.org/profile#hasMappedLocationWayID
     */
     
    public Collection<? extends Long> getHasMappedLocationWayID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONWAYID, Long.class);
    }

    public boolean hasHasMappedLocationWayID() {
		return !getHasMappedLocationWayID().isEmpty();
    }

    public void addHasMappedLocationWayID(Long newHasMappedLocationWayID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONWAYID, newHasMappedLocationWayID);
    }

    public void removeHasMappedLocationWayID(Long oldHasMappedLocationWayID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAPPEDLOCATIONWAYID, oldHasMappedLocationWayID);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#latitude
     */
     
    public Collection<? extends Object> getLatitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LATITUDE, Object.class);
    }

    public boolean hasLatitude() {
		return !getLatitude().isEmpty();
    }

    public void addLatitude(Object newLatitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LATITUDE, newLatitude);
    }

    public void removeLatitude(Object oldLatitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LATITUDE, oldLatitude);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2006/vcard/ns#longitude
     */
     
    public Collection<? extends Object> getLongitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LONGITUDE, Object.class);
    }

    public boolean hasLongitude() {
		return !getLongitude().isEmpty();
    }

    public void addLongitude(Object newLongitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LONGITUDE, newLongitude);
    }

    public void removeLongitude(Object oldLongitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LONGITUDE, oldLongitude);
    }


}
