package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Accompanying <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface Accompanying extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyTrip1
     */
     
    /**
     * Gets all property values for the hasAccompanyTrip1 property.<p>
     * 
     * @returns a collection of values for the hasAccompanyTrip1 property.
     */
    Collection<? extends TripMeasurement> getHasAccompanyTrip1();

    /**
     * Checks if the class has a hasAccompanyTrip1 property value.<p>
     * 
     * @return true if there is a hasAccompanyTrip1 property value.
     */
    boolean hasHasAccompanyTrip1();

    /**
     * Adds a hasAccompanyTrip1 property value.<p>
     * 
     * @param newHasAccompanyTrip1 the hasAccompanyTrip1 property value to be added
     */
    void addHasAccompanyTrip1(TripMeasurement newHasAccompanyTrip1);

    /**
     * Removes a hasAccompanyTrip1 property value.<p>
     * 
     * @param oldHasAccompanyTrip1 the hasAccompanyTrip1 property value to be removed.
     */
    void removeHasAccompanyTrip1(TripMeasurement oldHasAccompanyTrip1);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyTrip2
     */
     
    /**
     * Gets all property values for the hasAccompanyTrip2 property.<p>
     * 
     * @returns a collection of values for the hasAccompanyTrip2 property.
     */
    Collection<? extends TripMeasurement> getHasAccompanyTrip2();

    /**
     * Checks if the class has a hasAccompanyTrip2 property value.<p>
     * 
     * @return true if there is a hasAccompanyTrip2 property value.
     */
    boolean hasHasAccompanyTrip2();

    /**
     * Adds a hasAccompanyTrip2 property value.<p>
     * 
     * @param newHasAccompanyTrip2 the hasAccompanyTrip2 property value to be added
     */
    void addHasAccompanyTrip2(TripMeasurement newHasAccompanyTrip2);

    /**
     * Removes a hasAccompanyTrip2 property value.<p>
     * 
     * @param oldHasAccompanyTrip2 the hasAccompanyTrip2 property value to be removed.
     */
    void removeHasAccompanyTrip2(TripMeasurement oldHasAccompanyTrip2);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyDomainName
     */
     
    /**
     * Gets all property values for the hasAccompanyDomainName property.<p>
     * 
     * @returns a collection of values for the hasAccompanyDomainName property.
     */
    Collection<? extends String> getHasAccompanyDomainName();

    /**
     * Checks if the class has a hasAccompanyDomainName property value.<p>
     * 
     * @return true if there is a hasAccompanyDomainName property value.
     */
    boolean hasHasAccompanyDomainName();

    /**
     * Adds a hasAccompanyDomainName property value.<p>
     * 
     * @param newHasAccompanyDomainName the hasAccompanyDomainName property value to be added
     */
    void addHasAccompanyDomainName(String newHasAccompanyDomainName);

    /**
     * Removes a hasAccompanyDomainName property value.<p>
     * 
     * @param oldHasAccompanyDomainName the hasAccompanyDomainName property value to be removed.
     */
    void removeHasAccompanyDomainName(String oldHasAccompanyDomainName);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyID
     */
     
    /**
     * Gets all property values for the hasAccompanyID property.<p>
     * 
     * @returns a collection of values for the hasAccompanyID property.
     */
    Collection<? extends Long> getHasAccompanyID();

    /**
     * Checks if the class has a hasAccompanyID property value.<p>
     * 
     * @return true if there is a hasAccompanyID property value.
     */
    boolean hasHasAccompanyID();

    /**
     * Adds a hasAccompanyID property value.<p>
     * 
     * @param newHasAccompanyID the hasAccompanyID property value to be added
     */
    void addHasAccompanyID(Long newHasAccompanyID);

    /**
     * Removes a hasAccompanyID property value.<p>
     * 
     * @param oldHasAccompanyID the hasAccompanyID property value to be removed.
     */
    void removeHasAccompanyID(Long oldHasAccompanyID);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyScore
     */
     
    /**
     * Gets all property values for the hasAccompanyScore property.<p>
     * 
     * @returns a collection of values for the hasAccompanyScore property.
     */
    Collection<? extends Object> getHasAccompanyScore();

    /**
     * Checks if the class has a hasAccompanyScore property value.<p>
     * 
     * @return true if there is a hasAccompanyScore property value.
     */
    boolean hasHasAccompanyScore();

    /**
     * Adds a hasAccompanyScore property value.<p>
     * 
     * @param newHasAccompanyScore the hasAccompanyScore property value to be added
     */
    void addHasAccompanyScore(Object newHasAccompanyScore);

    /**
     * Removes a hasAccompanyScore property value.<p>
     * 
     * @param oldHasAccompanyScore the hasAccompanyScore property value to be removed.
     */
    void removeHasAccompanyScore(Object oldHasAccompanyScore);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyTime
     */
     
    /**
     * Gets all property values for the hasAccompanyTime property.<p>
     * 
     * @returns a collection of values for the hasAccompanyTime property.
     */
    Collection<? extends Long> getHasAccompanyTime();

    /**
     * Checks if the class has a hasAccompanyTime property value.<p>
     * 
     * @return true if there is a hasAccompanyTime property value.
     */
    boolean hasHasAccompanyTime();

    /**
     * Adds a hasAccompanyTime property value.<p>
     * 
     * @param newHasAccompanyTime the hasAccompanyTime property value to be added
     */
    void addHasAccompanyTime(Long newHasAccompanyTime);

    /**
     * Removes a hasAccompanyTime property value.<p>
     * 
     * @param oldHasAccompanyTime the hasAccompanyTime property value to be removed.
     */
    void removeHasAccompanyTime(Long oldHasAccompanyTime);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyTimeZone
     */
     
    /**
     * Gets all property values for the hasAccompanyTimeZone property.<p>
     * 
     * @returns a collection of values for the hasAccompanyTimeZone property.
     */
    Collection<? extends Long> getHasAccompanyTimeZone();

    /**
     * Checks if the class has a hasAccompanyTimeZone property value.<p>
     * 
     * @return true if there is a hasAccompanyTimeZone property value.
     */
    boolean hasHasAccompanyTimeZone();

    /**
     * Adds a hasAccompanyTimeZone property value.<p>
     * 
     * @param newHasAccompanyTimeZone the hasAccompanyTimeZone property value to be added
     */
    void addHasAccompanyTimeZone(Long newHasAccompanyTimeZone);

    /**
     * Removes a hasAccompanyTimeZone property value.<p>
     * 
     * @param oldHasAccompanyTimeZone the hasAccompanyTimeZone property value to be removed.
     */
    void removeHasAccompanyTimeZone(Long oldHasAccompanyTimeZone);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyUserID1
     */
     
    /**
     * Gets all property values for the hasAccompanyUserID1 property.<p>
     * 
     * @returns a collection of values for the hasAccompanyUserID1 property.
     */
    Collection<? extends String> getHasAccompanyUserID1();

    /**
     * Checks if the class has a hasAccompanyUserID1 property value.<p>
     * 
     * @return true if there is a hasAccompanyUserID1 property value.
     */
    boolean hasHasAccompanyUserID1();

    /**
     * Adds a hasAccompanyUserID1 property value.<p>
     * 
     * @param newHasAccompanyUserID1 the hasAccompanyUserID1 property value to be added
     */
    void addHasAccompanyUserID1(String newHasAccompanyUserID1);

    /**
     * Removes a hasAccompanyUserID1 property value.<p>
     * 
     * @param oldHasAccompanyUserID1 the hasAccompanyUserID1 property value to be removed.
     */
    void removeHasAccompanyUserID1(String oldHasAccompanyUserID1);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyUserID2
     */
     
    /**
     * Gets all property values for the hasAccompanyUserID2 property.<p>
     * 
     * @returns a collection of values for the hasAccompanyUserID2 property.
     */
    Collection<? extends String> getHasAccompanyUserID2();

    /**
     * Checks if the class has a hasAccompanyUserID2 property value.<p>
     * 
     * @return true if there is a hasAccompanyUserID2 property value.
     */
    boolean hasHasAccompanyUserID2();

    /**
     * Adds a hasAccompanyUserID2 property value.<p>
     * 
     * @param newHasAccompanyUserID2 the hasAccompanyUserID2 property value to be added
     */
    void addHasAccompanyUserID2(String newHasAccompanyUserID2);

    /**
     * Removes a hasAccompanyUserID2 property value.<p>
     * 
     * @param oldHasAccompanyUserID2 the hasAccompanyUserID2 property value to be removed.
     */
    void removeHasAccompanyUserID2(String oldHasAccompanyUserID2);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasAccompanyValidity
     */
     
    /**
     * Gets all property values for the hasAccompanyValidity property.<p>
     * 
     * @returns a collection of values for the hasAccompanyValidity property.
     */
    Collection<? extends Long> getHasAccompanyValidity();

    /**
     * Checks if the class has a hasAccompanyValidity property value.<p>
     * 
     * @return true if there is a hasAccompanyValidity property value.
     */
    boolean hasHasAccompanyValidity();

    /**
     * Adds a hasAccompanyValidity property value.<p>
     * 
     * @param newHasAccompanyValidity the hasAccompanyValidity property value to be added
     */
    void addHasAccompanyValidity(Long newHasAccompanyValidity);

    /**
     * Removes a hasAccompanyValidity property value.<p>
     * 
     * @param oldHasAccompanyValidity the hasAccompanyValidity property value to be removed.
     */
    void removeHasAccompanyValidity(Long oldHasAccompanyValidity);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasDecisionLevel
     */
     
    /**
     * Gets all property values for the hasDecisionLevel property.<p>
     * 
     * @returns a collection of values for the hasDecisionLevel property.
     */
    Collection<? extends Object> getHasDecisionLevel();

    /**
     * Checks if the class has a hasDecisionLevel property value.<p>
     * 
     * @return true if there is a hasDecisionLevel property value.
     */
    boolean hasHasDecisionLevel();

    /**
     * Adds a hasDecisionLevel property value.<p>
     * 
     * @param newHasDecisionLevel the hasDecisionLevel property value to be added
     */
    void addHasDecisionLevel(Object newHasDecisionLevel);

    /**
     * Removes a hasDecisionLevel property value.<p>
     * 
     * @param oldHasDecisionLevel the hasDecisionLevel property value to be removed.
     */
    void removeHasDecisionLevel(Object oldHasDecisionLevel);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
