package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Address <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface Address extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#townName
     */
     
    /**
     * Gets all property values for the townName property.<p>
     * 
     * @returns a collection of values for the townName property.
     */
    Collection<? extends String> getTownName();

    /**
     * Checks if the class has a townName property value.<p>
     * 
     * @return true if there is a townName property value.
     */
    boolean hasTownName();

    /**
     * Adds a townName property value.<p>
     * 
     * @param newTownName the townName property value to be added
     */
    void addTownName(String newTownName);

    /**
     * Removes a townName property value.<p>
     * 
     * @param oldTownName the townName property value to be removed.
     */
    void removeTownName(String oldTownName);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#country-name
     */
     
    /**
     * Gets all property values for the country_name property.<p>
     * 
     * @returns a collection of values for the country_name property.
     */
    Collection<? extends Object> getCountry_name();

    /**
     * Checks if the class has a country_name property value.<p>
     * 
     * @return true if there is a country_name property value.
     */
    boolean hasCountry_name();

    /**
     * Adds a country_name property value.<p>
     * 
     * @param newCountry_name the country_name property value to be added
     */
    void addCountry_name(Object newCountry_name);

    /**
     * Removes a country_name property value.<p>
     * 
     * @param oldCountry_name the country_name property value to be removed.
     */
    void removeCountry_name(Object oldCountry_name);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#latitude
     */
     
    /**
     * Gets all property values for the latitude property.<p>
     * 
     * @returns a collection of values for the latitude property.
     */
    Collection<? extends Object> getLatitude();

    /**
     * Checks if the class has a latitude property value.<p>
     * 
     * @return true if there is a latitude property value.
     */
    boolean hasLatitude();

    /**
     * Adds a latitude property value.<p>
     * 
     * @param newLatitude the latitude property value to be added
     */
    void addLatitude(Object newLatitude);

    /**
     * Removes a latitude property value.<p>
     * 
     * @param oldLatitude the latitude property value to be removed.
     */
    void removeLatitude(Object oldLatitude);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#longitude
     */
     
    /**
     * Gets all property values for the longitude property.<p>
     * 
     * @returns a collection of values for the longitude property.
     */
    Collection<? extends Object> getLongitude();

    /**
     * Checks if the class has a longitude property value.<p>
     * 
     * @return true if there is a longitude property value.
     */
    boolean hasLongitude();

    /**
     * Adds a longitude property value.<p>
     * 
     * @param newLongitude the longitude property value to be added
     */
    void addLongitude(Object newLongitude);

    /**
     * Removes a longitude property value.<p>
     * 
     * @param oldLongitude the longitude property value to be removed.
     */
    void removeLongitude(Object oldLongitude);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#post-office-box
     */
     
    /**
     * Gets all property values for the post_office_box property.<p>
     * 
     * @returns a collection of values for the post_office_box property.
     */
    Collection<? extends String> getPost_office_box();

    /**
     * Checks if the class has a post_office_box property value.<p>
     * 
     * @return true if there is a post_office_box property value.
     */
    boolean hasPost_office_box();

    /**
     * Adds a post_office_box property value.<p>
     * 
     * @param newPost_office_box the post_office_box property value to be added
     */
    void addPost_office_box(String newPost_office_box);

    /**
     * Removes a post_office_box property value.<p>
     * 
     * @param oldPost_office_box the post_office_box property value to be removed.
     */
    void removePost_office_box(String oldPost_office_box);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#postal-code
     */
     
    /**
     * Gets all property values for the postal_code property.<p>
     * 
     * @returns a collection of values for the postal_code property.
     */
    Collection<? extends Object> getPostal_code();

    /**
     * Checks if the class has a postal_code property value.<p>
     * 
     * @return true if there is a postal_code property value.
     */
    boolean hasPostal_code();

    /**
     * Adds a postal_code property value.<p>
     * 
     * @param newPostal_code the postal_code property value to be added
     */
    void addPostal_code(Object newPostal_code);

    /**
     * Removes a postal_code property value.<p>
     * 
     * @param oldPostal_code the postal_code property value to be removed.
     */
    void removePostal_code(Object oldPostal_code);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#street-address
     */
     
    /**
     * Gets all property values for the street_address property.<p>
     * 
     * @returns a collection of values for the street_address property.
     */
    Collection<? extends Object> getStreet_address();

    /**
     * Checks if the class has a street_address property value.<p>
     * 
     * @return true if there is a street_address property value.
     */
    boolean hasStreet_address();

    /**
     * Adds a street_address property value.<p>
     * 
     * @param newStreet_address the street_address property value to be added
     */
    void addStreet_address(Object newStreet_address);

    /**
     * Removes a street_address property value.<p>
     * 
     * @param oldStreet_address the street_address property value to be removed.
     */
    void removeStreet_address(Object oldStreet_address);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
