package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Course <br>
 * @version generated on Mon Jun 02 16:02:21 CEST 2014 by ragarwal
 */

public interface Course extends EventDetails {

    /* ***************************************************
     * Property http://linkedevents.org/ontology/atPlace
     */
     
    /**
     * Gets all property values for the at_place property.<p>
     * 
     * @returns a collection of values for the at_place property.
     */
    Collection<? extends Address> getAt_place();

    /**
     * Checks if the class has a at_place property value.<p>
     * 
     * @return true if there is a at_place property value.
     */
    boolean hasAt_place();

    /**
     * Adds a at_place property value.<p>
     * 
     * @param newAt_place the at_place property value to be added
     */
    void addAt_place(Address newAt_place);

    /**
     * Removes a at_place property value.<p>
     * 
     * @param oldAt_place the at_place property value to be removed.
     */
    void removeAt_place(Address oldAt_place);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasTemporalDetails
     */
     
    /**
     * Gets all property values for the hasTemporalDetails property.<p>
     * 
     * @returns a collection of values for the hasTemporalDetails property.
     */
    Collection<? extends TemporalDetails> getHasTemporalDetails();

    /**
     * Checks if the class has a hasTemporalDetails property value.<p>
     * 
     * @return true if there is a hasTemporalDetails property value.
     */
    boolean hasHasTemporalDetails();

    /**
     * Adds a hasTemporalDetails property value.<p>
     * 
     * @param newHasTemporalDetails the hasTemporalDetails property value to be added
     */
    void addHasTemporalDetails(TemporalDetails newHasTemporalDetails);

    /**
     * Removes a hasTemporalDetails property value.<p>
     * 
     * @param oldHasTemporalDetails the hasTemporalDetails property value to be removed.
     */
    void removeHasTemporalDetails(TemporalDetails oldHasTemporalDetails);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#isOfferedBy
     */
     
    /**
     * Gets all property values for the isOfferedBy property.<p>
     * 
     * @returns a collection of values for the isOfferedBy property.
     */
    Collection<? extends School> getIsOfferedBy();

    /**
     * Checks if the class has a isOfferedBy property value.<p>
     * 
     * @return true if there is a isOfferedBy property value.
     */
    boolean hasIsOfferedBy();

    /**
     * Adds a isOfferedBy property value.<p>
     * 
     * @param newIsOfferedBy the isOfferedBy property value to be added
     */
    void addIsOfferedBy(School newIsOfferedBy);

    /**
     * Removes a isOfferedBy property value.<p>
     * 
     * @param oldIsOfferedBy the isOfferedBy property value to be removed.
     */
    void removeIsOfferedBy(School oldIsOfferedBy);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasCourseDuration
     */
     
    /**
     * Gets all property values for the hasCourseDuration property.<p>
     * 
     * @returns a collection of values for the hasCourseDuration property.
     */
    Collection<? extends String> getHasCourseDuration();

    /**
     * Checks if the class has a hasCourseDuration property value.<p>
     * 
     * @return true if there is a hasCourseDuration property value.
     */
    boolean hasHasCourseDuration();

    /**
     * Adds a hasCourseDuration property value.<p>
     * 
     * @param newHasCourseDuration the hasCourseDuration property value to be added
     */
    void addHasCourseDuration(String newHasCourseDuration);

    /**
     * Removes a hasCourseDuration property value.<p>
     * 
     * @param oldHasCourseDuration the hasCourseDuration property value to be removed.
     */
    void removeHasCourseDuration(String oldHasCourseDuration);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasCourseInstructor
     */
     
    /**
     * Gets all property values for the hasCourseInstructor property.<p>
     * 
     * @returns a collection of values for the hasCourseInstructor property.
     */
    Collection<? extends String> getHasCourseInstructor();

    /**
     * Checks if the class has a hasCourseInstructor property value.<p>
     * 
     * @return true if there is a hasCourseInstructor property value.
     */
    boolean hasHasCourseInstructor();

    /**
     * Adds a hasCourseInstructor property value.<p>
     * 
     * @param newHasCourseInstructor the hasCourseInstructor property value to be added
     */
    void addHasCourseInstructor(String newHasCourseInstructor);

    /**
     * Removes a hasCourseInstructor property value.<p>
     * 
     * @param oldHasCourseInstructor the hasCourseInstructor property value to be removed.
     */
    void removeHasCourseInstructor(String oldHasCourseInstructor);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasCourseName
     */
     
    /**
     * Gets all property values for the hasCourseName property.<p>
     * 
     * @returns a collection of values for the hasCourseName property.
     */
    Collection<? extends String> getHasCourseName();

    /**
     * Checks if the class has a hasCourseName property value.<p>
     * 
     * @return true if there is a hasCourseName property value.
     */
    boolean hasHasCourseName();

    /**
     * Adds a hasCourseName property value.<p>
     * 
     * @param newHasCourseName the hasCourseName property value to be added
     */
    void addHasCourseName(String newHasCourseName);

    /**
     * Removes a hasCourseName property value.<p>
     * 
     * @param oldHasCourseName the hasCourseName property value to be removed.
     */
    void removeHasCourseName(String oldHasCourseName);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasCourseType
     */
     
    /**
     * Gets all property values for the hasCourseType property.<p>
     * 
     * @returns a collection of values for the hasCourseType property.
     */
    Collection<? extends Object> getHasCourseType();

    /**
     * Checks if the class has a hasCourseType property value.<p>
     * 
     * @return true if there is a hasCourseType property value.
     */
    boolean hasHasCourseType();

    /**
     * Adds a hasCourseType property value.<p>
     * 
     * @param newHasCourseType the hasCourseType property value to be added
     */
    void addHasCourseType(Object newHasCourseType);

    /**
     * Removes a hasCourseType property value.<p>
     * 
     * @param oldHasCourseType the hasCourseType property value to be removed.
     */
    void removeHasCourseType(Object oldHasCourseType);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasDetail
     */
     
    /**
     * Gets all property values for the hasDetail property.<p>
     * 
     * @returns a collection of values for the hasDetail property.
     */
    Collection<? extends String> getHasDetail();

    /**
     * Checks if the class has a hasDetail property value.<p>
     * 
     * @return true if there is a hasDetail property value.
     */
    boolean hasHasDetail();

    /**
     * Adds a hasDetail property value.<p>
     * 
     * @param newHasDetail the hasDetail property value to be added
     */
    void addHasDetail(String newHasDetail);

    /**
     * Removes a hasDetail property value.<p>
     * 
     * @param oldHasDetail the hasDetail property value to be removed.
     */
    void removeHasDetail(String oldHasDetail);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasEventName
     */
     
    /**
     * Gets all property values for the hasEventName property.<p>
     * 
     * @returns a collection of values for the hasEventName property.
     */
    Collection<? extends String> getHasEventName();

    /**
     * Checks if the class has a hasEventName property value.<p>
     * 
     * @return true if there is a hasEventName property value.
     */
    boolean hasHasEventName();

    /**
     * Adds a hasEventName property value.<p>
     * 
     * @param newHasEventName the hasEventName property value to be added
     */
    void addHasEventName(String newHasEventName);

    /**
     * Removes a hasEventName property value.<p>
     * 
     * @param oldHasEventName the hasEventName property value to be removed.
     */
    void removeHasEventName(String oldHasEventName);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasKeyTags
     */
     
    /**
     * Gets all property values for the hasKeyTags property.<p>
     * 
     * @returns a collection of values for the hasKeyTags property.
     */
    Collection<? extends String> getHasKeyTags();

    /**
     * Checks if the class has a hasKeyTags property value.<p>
     * 
     * @return true if there is a hasKeyTags property value.
     */
    boolean hasHasKeyTags();

    /**
     * Adds a hasKeyTags property value.<p>
     * 
     * @param newHasKeyTags the hasKeyTags property value to be added
     */
    void addHasKeyTags(String newHasKeyTags);

    /**
     * Removes a hasKeyTags property value.<p>
     * 
     * @param oldHasKeyTags the hasKeyTags property value to be removed.
     */
    void removeHasKeyTags(String oldHasKeyTags);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNatureOfEvent
     */
     
    /**
     * Gets all property values for the hasNatureOfEvent property.<p>
     * 
     * @returns a collection of values for the hasNatureOfEvent property.
     */
    Collection<? extends Object> getHasNatureOfEvent();

    /**
     * Checks if the class has a hasNatureOfEvent property value.<p>
     * 
     * @return true if there is a hasNatureOfEvent property value.
     */
    boolean hasHasNatureOfEvent();

    /**
     * Adds a hasNatureOfEvent property value.<p>
     * 
     * @param newHasNatureOfEvent the hasNatureOfEvent property value to be added
     */
    void addHasNatureOfEvent(Object newHasNatureOfEvent);

    /**
     * Removes a hasNatureOfEvent property value.<p>
     * 
     * @param oldHasNatureOfEvent the hasNatureOfEvent property value to be removed.
     */
    void removeHasNatureOfEvent(Object oldHasNatureOfEvent);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
