package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: EventDetailPreference <br>
 * @version generated on Mon Jun 02 16:02:21 CEST 2014 by ragarwal
 */

public interface EventDetailPreference extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNatureOfEvent
     */
     
    /**
     * Gets all property values for the hasNatureOfEvent property.<p>
     * 
     * @returns a collection of values for the hasNatureOfEvent property.
     */
    Collection<? extends Object> getHasNatureOfEvent();

    /**
     * Checks if the class has a hasNatureOfEvent property value.<p>
     * 
     * @return true if there is a hasNatureOfEvent property value.
     */
    boolean hasHasNatureOfEvent();

    /**
     * Adds a hasNatureOfEvent property value.<p>
     * 
     * @param newHasNatureOfEvent the hasNatureOfEvent property value to be added
     */
    void addHasNatureOfEvent(Object newHasNatureOfEvent);

    /**
     * Removes a hasNatureOfEvent property value.<p>
     * 
     * @param oldHasNatureOfEvent the hasNatureOfEvent property value to be removed.
     */
    void removeHasNatureOfEvent(Object oldHasNatureOfEvent);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredEndDate
     */
     
    /**
     * Gets all property values for the hasPreferredEndDate property.<p>
     * 
     * @returns a collection of values for the hasPreferredEndDate property.
     */
    Collection<? extends Object> getHasPreferredEndDate();

    /**
     * Checks if the class has a hasPreferredEndDate property value.<p>
     * 
     * @return true if there is a hasPreferredEndDate property value.
     */
    boolean hasHasPreferredEndDate();

    /**
     * Adds a hasPreferredEndDate property value.<p>
     * 
     * @param newHasPreferredEndDate the hasPreferredEndDate property value to be added
     */
    void addHasPreferredEndDate(Object newHasPreferredEndDate);

    /**
     * Removes a hasPreferredEndDate property value.<p>
     * 
     * @param oldHasPreferredEndDate the hasPreferredEndDate property value to be removed.
     */
    void removeHasPreferredEndDate(Object oldHasPreferredEndDate);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredEventKeyTags
     */
     
    /**
     * Gets all property values for the hasPreferredEventKeyTags property.<p>
     * 
     * @returns a collection of values for the hasPreferredEventKeyTags property.
     */
    Collection<? extends String> getHasPreferredEventKeyTags();

    /**
     * Checks if the class has a hasPreferredEventKeyTags property value.<p>
     * 
     * @return true if there is a hasPreferredEventKeyTags property value.
     */
    boolean hasHasPreferredEventKeyTags();

    /**
     * Adds a hasPreferredEventKeyTags property value.<p>
     * 
     * @param newHasPreferredEventKeyTags the hasPreferredEventKeyTags property value to be added
     */
    void addHasPreferredEventKeyTags(String newHasPreferredEventKeyTags);

    /**
     * Removes a hasPreferredEventKeyTags property value.<p>
     * 
     * @param oldHasPreferredEventKeyTags the hasPreferredEventKeyTags property value to be removed.
     */
    void removeHasPreferredEventKeyTags(String oldHasPreferredEventKeyTags);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredStartDate
     */
     
    /**
     * Gets all property values for the hasPreferredStartDate property.<p>
     * 
     * @returns a collection of values for the hasPreferredStartDate property.
     */
    Collection<? extends Object> getHasPreferredStartDate();

    /**
     * Checks if the class has a hasPreferredStartDate property value.<p>
     * 
     * @return true if there is a hasPreferredStartDate property value.
     */
    boolean hasHasPreferredStartDate();

    /**
     * Adds a hasPreferredStartDate property value.<p>
     * 
     * @param newHasPreferredStartDate the hasPreferredStartDate property value to be added
     */
    void addHasPreferredStartDate(Object newHasPreferredStartDate);

    /**
     * Removes a hasPreferredStartDate property value.<p>
     * 
     * @param oldHasPreferredStartDate the hasPreferredStartDate property value to be removed.
     */
    void removeHasPreferredStartDate(Object oldHasPreferredStartDate);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
