package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: HotelPreference <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface HotelPreference extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasHotelDetailPreference
     */
     
    /**
     * Gets all property values for the hasHotelDetailPreference property.<p>
     * 
     * @returns a collection of values for the hasHotelDetailPreference property.
     */
    Collection<? extends HotelDetailPreference> getHasHotelDetailPreference();

    /**
     * Checks if the class has a hasHotelDetailPreference property value.<p>
     * 
     * @return true if there is a hasHotelDetailPreference property value.
     */
    boolean hasHasHotelDetailPreference();

    /**
     * Adds a hasHotelDetailPreference property value.<p>
     * 
     * @param newHasHotelDetailPreference the hasHotelDetailPreference property value to be added
     */
    void addHasHotelDetailPreference(HotelDetailPreference newHasHotelDetailPreference);

    /**
     * Removes a hasHotelDetailPreference property value.<p>
     * 
     * @param oldHasHotelDetailPreference the hasHotelDetailPreference property value to be removed.
     */
    void removeHasHotelDetailPreference(HotelDetailPreference oldHasHotelDetailPreference);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredHotelRating
     */
     
    /**
     * Gets all property values for the hasPreferredHotelRating property.<p>
     * 
     * @returns a collection of values for the hasPreferredHotelRating property.
     */
    Collection<? extends RatingPreference> getHasPreferredHotelRating();

    /**
     * Checks if the class has a hasPreferredHotelRating property value.<p>
     * 
     * @return true if there is a hasPreferredHotelRating property value.
     */
    boolean hasHasPreferredHotelRating();

    /**
     * Adds a hasPreferredHotelRating property value.<p>
     * 
     * @param newHasPreferredHotelRating the hasPreferredHotelRating property value to be added
     */
    void addHasPreferredHotelRating(RatingPreference newHasPreferredHotelRating);

    /**
     * Removes a hasPreferredHotelRating property value.<p>
     * 
     * @param oldHasPreferredHotelRating the hasPreferredHotelRating property value to be removed.
     */
    void removeHasPreferredHotelRating(RatingPreference oldHasPreferredHotelRating);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNumberOfTimesVisited
     */
     
    /**
     * Gets all property values for the hasNumberOfTimesVisited property.<p>
     * 
     * @returns a collection of values for the hasNumberOfTimesVisited property.
     */
    Collection<? extends Integer> getHasNumberOfTimesVisited();

    /**
     * Checks if the class has a hasNumberOfTimesVisited property value.<p>
     * 
     * @return true if there is a hasNumberOfTimesVisited property value.
     */
    boolean hasHasNumberOfTimesVisited();

    /**
     * Adds a hasNumberOfTimesVisited property value.<p>
     * 
     * @param newHasNumberOfTimesVisited the hasNumberOfTimesVisited property value to be added
     */
    void addHasNumberOfTimesVisited(Integer newHasNumberOfTimesVisited);

    /**
     * Removes a hasNumberOfTimesVisited property value.<p>
     * 
     * @param oldHasNumberOfTimesVisited the hasNumberOfTimesVisited property value to be removed.
     */
    void removeHasNumberOfTimesVisited(Integer oldHasNumberOfTimesVisited);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
