package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: HotelDetail <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface HotelDetail extends PlaceDetail {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasHotelChains
     */
     
    /**
     * Gets all property values for the hasHotelChains property.<p>
     * 
     * @returns a collection of values for the hasHotelChains property.
     */
    Collection<? extends Address> getHasHotelChains();

    /**
     * Checks if the class has a hasHotelChains property value.<p>
     * 
     * @return true if there is a hasHotelChains property value.
     */
    boolean hasHasHotelChains();

    /**
     * Adds a hasHotelChains property value.<p>
     * 
     * @param newHasHotelChains the hasHotelChains property value to be added
     */
    void addHasHotelChains(Address newHasHotelChains);

    /**
     * Removes a hasHotelChains property value.<p>
     * 
     * @param oldHasHotelChains the hasHotelChains property value to be removed.
     */
    void removeHasHotelChains(Address oldHasHotelChains);


    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#hasAddress
     */
     
    /**
     * Gets all property values for the has_address property.<p>
     * 
     * @returns a collection of values for the has_address property.
     */
    Collection<? extends WrappedIndividual> getHas_address();

    /**
     * Checks if the class has a has_address property value.<p>
     * 
     * @return true if there is a has_address property value.
     */
    boolean hasHas_address();

    /**
     * Adds a has_address property value.<p>
     * 
     * @param newHas_address the has_address property value to be added
     */
    void addHas_address(WrappedIndividual newHas_address);

    /**
     * Removes a has_address property value.<p>
     * 
     * @param oldHas_address the has_address property value to be removed.
     */
    void removeHas_address(WrappedIndividual oldHas_address);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasHotelPriceHigh
     */
     
    /**
     * Gets all property values for the hasHotelPriceHigh property.<p>
     * 
     * @returns a collection of values for the hasHotelPriceHigh property.
     */
    Collection<? extends Object> getHasHotelPriceHigh();

    /**
     * Checks if the class has a hasHotelPriceHigh property value.<p>
     * 
     * @return true if there is a hasHotelPriceHigh property value.
     */
    boolean hasHasHotelPriceHigh();

    /**
     * Adds a hasHotelPriceHigh property value.<p>
     * 
     * @param newHasHotelPriceHigh the hasHotelPriceHigh property value to be added
     */
    void addHasHotelPriceHigh(Object newHasHotelPriceHigh);

    /**
     * Removes a hasHotelPriceHigh property value.<p>
     * 
     * @param oldHasHotelPriceHigh the hasHotelPriceHigh property value to be removed.
     */
    void removeHasHotelPriceHigh(Object oldHasHotelPriceHigh);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasHotelPriceLow
     */
     
    /**
     * Gets all property values for the hasHotelPriceLow property.<p>
     * 
     * @returns a collection of values for the hasHotelPriceLow property.
     */
    Collection<? extends Object> getHasHotelPriceLow();

    /**
     * Checks if the class has a hasHotelPriceLow property value.<p>
     * 
     * @return true if there is a hasHotelPriceLow property value.
     */
    boolean hasHasHotelPriceLow();

    /**
     * Adds a hasHotelPriceLow property value.<p>
     * 
     * @param newHasHotelPriceLow the hasHotelPriceLow property value to be added
     */
    void addHasHotelPriceLow(Object newHasHotelPriceLow);

    /**
     * Removes a hasHotelPriceLow property value.<p>
     * 
     * @param oldHasHotelPriceLow the hasHotelPriceLow property value to be removed.
     */
    void removeHasHotelPriceLow(Object oldHasHotelPriceLow);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasHotelRoomType
     */
     
    /**
     * Gets all property values for the hasHotelRoomType property.<p>
     * 
     * @returns a collection of values for the hasHotelRoomType property.
     */
    Collection<? extends Object> getHasHotelRoomType();

    /**
     * Checks if the class has a hasHotelRoomType property value.<p>
     * 
     * @return true if there is a hasHotelRoomType property value.
     */
    boolean hasHasHotelRoomType();

    /**
     * Adds a hasHotelRoomType property value.<p>
     * 
     * @param newHasHotelRoomType the hasHotelRoomType property value to be added
     */
    void addHasHotelRoomType(Object newHasHotelRoomType);

    /**
     * Removes a hasHotelRoomType property value.<p>
     * 
     * @param oldHasHotelRoomType the hasHotelRoomType property value to be removed.
     */
    void removeHasHotelRoomType(Object oldHasHotelRoomType);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasHotelStarCategory
     */
     
    /**
     * Gets all property values for the hasHotelStarCategory property.<p>
     * 
     * @returns a collection of values for the hasHotelStarCategory property.
     */
    Collection<? extends Object> getHasHotelStarCategory();

    /**
     * Checks if the class has a hasHotelStarCategory property value.<p>
     * 
     * @return true if there is a hasHotelStarCategory property value.
     */
    boolean hasHasHotelStarCategory();

    /**
     * Adds a hasHotelStarCategory property value.<p>
     * 
     * @param newHasHotelStarCategory the hasHotelStarCategory property value to be added
     */
    void addHasHotelStarCategory(Object newHasHotelStarCategory);

    /**
     * Removes a hasHotelStarCategory property value.<p>
     * 
     * @param oldHasHotelStarCategory the hasHotelStarCategory property value to be removed.
     */
    void removeHasHotelStarCategory(Object oldHasHotelStarCategory);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasKeyTags
     */
     
    /**
     * Gets all property values for the hasKeyTags property.<p>
     * 
     * @returns a collection of values for the hasKeyTags property.
     */
    Collection<? extends String> getHasKeyTags();

    /**
     * Checks if the class has a hasKeyTags property value.<p>
     * 
     * @return true if there is a hasKeyTags property value.
     */
    boolean hasHasKeyTags();

    /**
     * Adds a hasKeyTags property value.<p>
     * 
     * @param newHasKeyTags the hasKeyTags property value to be added
     */
    void addHasKeyTags(String newHasKeyTags);

    /**
     * Removes a hasKeyTags property value.<p>
     * 
     * @param oldHasKeyTags the hasKeyTags property value to be removed.
     */
    void removeHasKeyTags(String oldHasKeyTags);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNatureOfPlace
     */
     
    /**
     * Gets all property values for the hasNatureOfPlace property.<p>
     * 
     * @returns a collection of values for the hasNatureOfPlace property.
     */
    Collection<? extends Object> getHasNatureOfPlace();

    /**
     * Checks if the class has a hasNatureOfPlace property value.<p>
     * 
     * @return true if there is a hasNatureOfPlace property value.
     */
    boolean hasHasNatureOfPlace();

    /**
     * Adds a hasNatureOfPlace property value.<p>
     * 
     * @param newHasNatureOfPlace the hasNatureOfPlace property value to be added
     */
    void addHasNatureOfPlace(Object newHasNatureOfPlace);

    /**
     * Removes a hasNatureOfPlace property value.<p>
     * 
     * @param oldHasNatureOfPlace the hasNatureOfPlace property value to be removed.
     */
    void removeHasNatureOfPlace(Object oldHasNatureOfPlace);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNearByTransportMode
     */
     
    /**
     * Gets all property values for the hasNearByTransportMode property.<p>
     * 
     * @returns a collection of values for the hasNearByTransportMode property.
     */
    Collection<? extends String> getHasNearByTransportMode();

    /**
     * Checks if the class has a hasNearByTransportMode property value.<p>
     * 
     * @return true if there is a hasNearByTransportMode property value.
     */
    boolean hasHasNearByTransportMode();

    /**
     * Adds a hasNearByTransportMode property value.<p>
     * 
     * @param newHasNearByTransportMode the hasNearByTransportMode property value to be added
     */
    void addHasNearByTransportMode(String newHasNearByTransportMode);

    /**
     * Removes a hasNearByTransportMode property value.<p>
     * 
     * @param oldHasNearByTransportMode the hasNearByTransportMode property value to be removed.
     */
    void removeHasNearByTransportMode(String oldHasNearByTransportMode);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPlaceName
     */
     
    /**
     * Gets all property values for the hasPlaceName property.<p>
     * 
     * @returns a collection of values for the hasPlaceName property.
     */
    Collection<? extends String> getHasPlaceName();

    /**
     * Checks if the class has a hasPlaceName property value.<p>
     * 
     * @return true if there is a hasPlaceName property value.
     */
    boolean hasHasPlaceName();

    /**
     * Adds a hasPlaceName property value.<p>
     * 
     * @param newHasPlaceName the hasPlaceName property value to be added
     */
    void addHasPlaceName(String newHasPlaceName);

    /**
     * Removes a hasPlaceName property value.<p>
     * 
     * @param oldHasPlaceName the hasPlaceName property value to be removed.
     */
    void removeHasPlaceName(String oldHasPlaceName);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasTypeOfFood
     */
     
    /**
     * Gets all property values for the hasTypeOfFood property.<p>
     * 
     * @returns a collection of values for the hasTypeOfFood property.
     */
    Collection<? extends Object> getHasTypeOfFood();

    /**
     * Checks if the class has a hasTypeOfFood property value.<p>
     * 
     * @return true if there is a hasTypeOfFood property value.
     */
    boolean hasHasTypeOfFood();

    /**
     * Adds a hasTypeOfFood property value.<p>
     * 
     * @param newHasTypeOfFood the hasTypeOfFood property value to be added
     */
    void addHasTypeOfFood(Object newHasTypeOfFood);

    /**
     * Removes a hasTypeOfFood property value.<p>
     * 
     * @param oldHasTypeOfFood the hasTypeOfFood property value to be removed.
     */
    void removeHasTypeOfFood(Object oldHasTypeOfFood);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
