package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: HotelDetailPreference <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface HotelDetailPreference extends PlaceDetailPreference {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredApproximateAddress
     */
     
    /**
     * Gets all property values for the hasPreferredApproximateAddress property.<p>
     * 
     * @returns a collection of values for the hasPreferredApproximateAddress property.
     */
    Collection<? extends Address> getHasPreferredApproximateAddress();

    /**
     * Checks if the class has a hasPreferredApproximateAddress property value.<p>
     * 
     * @return true if there is a hasPreferredApproximateAddress property value.
     */
    boolean hasHasPreferredApproximateAddress();

    /**
     * Adds a hasPreferredApproximateAddress property value.<p>
     * 
     * @param newHasPreferredApproximateAddress the hasPreferredApproximateAddress property value to be added
     */
    void addHasPreferredApproximateAddress(Address newHasPreferredApproximateAddress);

    /**
     * Removes a hasPreferredApproximateAddress property value.<p>
     * 
     * @param oldHasPreferredApproximateAddress the hasPreferredApproximateAddress property value to be removed.
     */
    void removeHasPreferredApproximateAddress(Address oldHasPreferredApproximateAddress);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredChains
     */
     
    /**
     * Gets all property values for the hasPreferredChains property.<p>
     * 
     * @returns a collection of values for the hasPreferredChains property.
     */
    Collection<? extends Address> getHasPreferredChains();

    /**
     * Checks if the class has a hasPreferredChains property value.<p>
     * 
     * @return true if there is a hasPreferredChains property value.
     */
    boolean hasHasPreferredChains();

    /**
     * Adds a hasPreferredChains property value.<p>
     * 
     * @param newHasPreferredChains the hasPreferredChains property value to be added
     */
    void addHasPreferredChains(Address newHasPreferredChains);

    /**
     * Removes a hasPreferredChains property value.<p>
     * 
     * @param oldHasPreferredChains the hasPreferredChains property value to be removed.
     */
    void removeHasPreferredChains(Address oldHasPreferredChains);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMaxPriceLow
     */
     
    /**
     * Gets all property values for the hasMaxPriceLow property.<p>
     * 
     * @returns a collection of values for the hasMaxPriceLow property.
     */
    Collection<? extends Object> getHasMaxPriceLow();

    /**
     * Checks if the class has a hasMaxPriceLow property value.<p>
     * 
     * @return true if there is a hasMaxPriceLow property value.
     */
    boolean hasHasMaxPriceLow();

    /**
     * Adds a hasMaxPriceLow property value.<p>
     * 
     * @param newHasMaxPriceLow the hasMaxPriceLow property value to be added
     */
    void addHasMaxPriceLow(Object newHasMaxPriceLow);

    /**
     * Removes a hasMaxPriceLow property value.<p>
     * 
     * @param oldHasMaxPriceLow the hasMaxPriceLow property value to be removed.
     */
    void removeHasMaxPriceLow(Object oldHasMaxPriceLow);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMinPriceHigh
     */
     
    /**
     * Gets all property values for the hasMinPriceHigh property.<p>
     * 
     * @returns a collection of values for the hasMinPriceHigh property.
     */
    Collection<? extends Object> getHasMinPriceHigh();

    /**
     * Checks if the class has a hasMinPriceHigh property value.<p>
     * 
     * @return true if there is a hasMinPriceHigh property value.
     */
    boolean hasHasMinPriceHigh();

    /**
     * Adds a hasMinPriceHigh property value.<p>
     * 
     * @param newHasMinPriceHigh the hasMinPriceHigh property value to be added
     */
    void addHasMinPriceHigh(Object newHasMinPriceHigh);

    /**
     * Removes a hasMinPriceHigh property value.<p>
     * 
     * @param oldHasMinPriceHigh the hasMinPriceHigh property value to be removed.
     */
    void removeHasMinPriceHigh(Object oldHasMinPriceHigh);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNatureOfPlace
     */
     
    /**
     * Gets all property values for the hasNatureOfPlace property.<p>
     * 
     * @returns a collection of values for the hasNatureOfPlace property.
     */
    Collection<? extends Object> getHasNatureOfPlace();

    /**
     * Checks if the class has a hasNatureOfPlace property value.<p>
     * 
     * @return true if there is a hasNatureOfPlace property value.
     */
    boolean hasHasNatureOfPlace();

    /**
     * Adds a hasNatureOfPlace property value.<p>
     * 
     * @param newHasNatureOfPlace the hasNatureOfPlace property value to be added
     */
    void addHasNatureOfPlace(Object newHasNatureOfPlace);

    /**
     * Removes a hasNatureOfPlace property value.<p>
     * 
     * @param oldHasNatureOfPlace the hasNatureOfPlace property value to be removed.
     */
    void removeHasNatureOfPlace(Object oldHasNatureOfPlace);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNearByTransportMode
     */
     
    /**
     * Gets all property values for the hasNearByTransportMode property.<p>
     * 
     * @returns a collection of values for the hasNearByTransportMode property.
     */
    Collection<? extends String> getHasNearByTransportMode();

    /**
     * Checks if the class has a hasNearByTransportMode property value.<p>
     * 
     * @return true if there is a hasNearByTransportMode property value.
     */
    boolean hasHasNearByTransportMode();

    /**
     * Adds a hasNearByTransportMode property value.<p>
     * 
     * @param newHasNearByTransportMode the hasNearByTransportMode property value to be added
     */
    void addHasNearByTransportMode(String newHasNearByTransportMode);

    /**
     * Removes a hasNearByTransportMode property value.<p>
     * 
     * @param oldHasNearByTransportMode the hasNearByTransportMode property value to be removed.
     */
    void removeHasNearByTransportMode(String oldHasNearByTransportMode);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredFacilities
     */
     
    /**
     * Gets all property values for the hasPreferredFacilities property.<p>
     * 
     * @returns a collection of values for the hasPreferredFacilities property.
     */
    Collection<? extends String> getHasPreferredFacilities();

    /**
     * Checks if the class has a hasPreferredFacilities property value.<p>
     * 
     * @return true if there is a hasPreferredFacilities property value.
     */
    boolean hasHasPreferredFacilities();

    /**
     * Adds a hasPreferredFacilities property value.<p>
     * 
     * @param newHasPreferredFacilities the hasPreferredFacilities property value to be added
     */
    void addHasPreferredFacilities(String newHasPreferredFacilities);

    /**
     * Removes a hasPreferredFacilities property value.<p>
     * 
     * @param oldHasPreferredFacilities the hasPreferredFacilities property value to be removed.
     */
    void removeHasPreferredFacilities(String oldHasPreferredFacilities);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredPlaceKeyTags
     */
     
    /**
     * Gets all property values for the hasPreferredPlaceKeyTags property.<p>
     * 
     * @returns a collection of values for the hasPreferredPlaceKeyTags property.
     */
    Collection<? extends String> getHasPreferredPlaceKeyTags();

    /**
     * Checks if the class has a hasPreferredPlaceKeyTags property value.<p>
     * 
     * @return true if there is a hasPreferredPlaceKeyTags property value.
     */
    boolean hasHasPreferredPlaceKeyTags();

    /**
     * Adds a hasPreferredPlaceKeyTags property value.<p>
     * 
     * @param newHasPreferredPlaceKeyTags the hasPreferredPlaceKeyTags property value to be added
     */
    void addHasPreferredPlaceKeyTags(String newHasPreferredPlaceKeyTags);

    /**
     * Removes a hasPreferredPlaceKeyTags property value.<p>
     * 
     * @param oldHasPreferredPlaceKeyTags the hasPreferredPlaceKeyTags property value to be removed.
     */
    void removeHasPreferredPlaceKeyTags(String oldHasPreferredPlaceKeyTags);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredRoomType
     */
     
    /**
     * Gets all property values for the hasPreferredRoomType property.<p>
     * 
     * @returns a collection of values for the hasPreferredRoomType property.
     */
    Collection<? extends Object> getHasPreferredRoomType();

    /**
     * Checks if the class has a hasPreferredRoomType property value.<p>
     * 
     * @return true if there is a hasPreferredRoomType property value.
     */
    boolean hasHasPreferredRoomType();

    /**
     * Adds a hasPreferredRoomType property value.<p>
     * 
     * @param newHasPreferredRoomType the hasPreferredRoomType property value to be added
     */
    void addHasPreferredRoomType(Object newHasPreferredRoomType);

    /**
     * Removes a hasPreferredRoomType property value.<p>
     * 
     * @param oldHasPreferredRoomType the hasPreferredRoomType property value to be removed.
     */
    void removeHasPreferredRoomType(Object oldHasPreferredRoomType);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredStarCategory
     */
     
    /**
     * Gets all property values for the hasPreferredStarCategory property.<p>
     * 
     * @returns a collection of values for the hasPreferredStarCategory property.
     */
    Collection<? extends Object> getHasPreferredStarCategory();

    /**
     * Checks if the class has a hasPreferredStarCategory property value.<p>
     * 
     * @return true if there is a hasPreferredStarCategory property value.
     */
    boolean hasHasPreferredStarCategory();

    /**
     * Adds a hasPreferredStarCategory property value.<p>
     * 
     * @param newHasPreferredStarCategory the hasPreferredStarCategory property value to be added
     */
    void addHasPreferredStarCategory(Object newHasPreferredStarCategory);

    /**
     * Removes a hasPreferredStarCategory property value.<p>
     * 
     * @param oldHasPreferredStarCategory the hasPreferredStarCategory property value to be removed.
     */
    void removeHasPreferredStarCategory(Object oldHasPreferredStarCategory);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasTypeOfFood
     */
     
    /**
     * Gets all property values for the hasTypeOfFood property.<p>
     * 
     * @returns a collection of values for the hasTypeOfFood property.
     */
    Collection<? extends Object> getHasTypeOfFood();

    /**
     * Checks if the class has a hasTypeOfFood property value.<p>
     * 
     * @return true if there is a hasTypeOfFood property value.
     */
    boolean hasHasTypeOfFood();

    /**
     * Adds a hasTypeOfFood property value.<p>
     * 
     * @param newHasTypeOfFood the hasTypeOfFood property value to be added
     */
    void addHasTypeOfFood(Object newHasTypeOfFood);

    /**
     * Removes a hasTypeOfFood property value.<p>
     * 
     * @param oldHasTypeOfFood the hasTypeOfFood property value to be removed.
     */
    void removeHasTypeOfFood(Object oldHasTypeOfFood);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
