package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Language <br>
 * @version generated on Wed Jun 25 09:55:40 CEST 2014 by ragarwal
 */

public interface Language extends LanguageDetails {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasKeyTags
     */
     
    /**
     * Gets all property values for the hasKeyTags property.<p>
     * 
     * @returns a collection of values for the hasKeyTags property.
     */
    Collection<? extends String> getHasKeyTags();

    /**
     * Checks if the class has a hasKeyTags property value.<p>
     * 
     * @return true if there is a hasKeyTags property value.
     */
    boolean hasHasKeyTags();

    /**
     * Adds a hasKeyTags property value.<p>
     * 
     * @param newHasKeyTags the hasKeyTags property value to be added
     */
    void addHasKeyTags(String newHasKeyTags);

    /**
     * Removes a hasKeyTags property value.<p>
     * 
     * @param oldHasKeyTags the hasKeyTags property value to be removed.
     */
    void removeHasKeyTags(String oldHasKeyTags);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasLanguageName
     */
     
    /**
     * Gets all property values for the hasLanguageName property.<p>
     * 
     * @returns a collection of values for the hasLanguageName property.
     */
    Collection<? extends String> getHasLanguageName();

    /**
     * Checks if the class has a hasLanguageName property value.<p>
     * 
     * @return true if there is a hasLanguageName property value.
     */
    boolean hasHasLanguageName();

    /**
     * Adds a hasLanguageName property value.<p>
     * 
     * @param newHasLanguageName the hasLanguageName property value to be added
     */
    void addHasLanguageName(String newHasLanguageName);

    /**
     * Removes a hasLanguageName property value.<p>
     * 
     * @param oldHasLanguageName the hasLanguageName property value to be removed.
     */
    void removeHasLanguageName(String oldHasLanguageName);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasLanguageState
     */
     
    /**
     * Gets all property values for the hasLanguageState property.<p>
     * 
     * @returns a collection of values for the hasLanguageState property.
     */
    Collection<? extends Object> getHasLanguageState();

    /**
     * Checks if the class has a hasLanguageState property value.<p>
     * 
     * @return true if there is a hasLanguageState property value.
     */
    boolean hasHasLanguageState();

    /**
     * Adds a hasLanguageState property value.<p>
     * 
     * @param newHasLanguageState the hasLanguageState property value to be added
     */
    void addHasLanguageState(Object newHasLanguageState);

    /**
     * Removes a hasLanguageState property value.<p>
     * 
     * @param oldHasLanguageState the hasLanguageState property value to be removed.
     */
    void removeHasLanguageState(Object oldHasLanguageState);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#wantsLanguageState
     */
     
    /**
     * Gets all property values for the wantsLanguageState property.<p>
     * 
     * @returns a collection of values for the wantsLanguageState property.
     */
    Collection<? extends Object> getWantsLanguageState();

    /**
     * Checks if the class has a wantsLanguageState property value.<p>
     * 
     * @return true if there is a wantsLanguageState property value.
     */
    boolean hasWantsLanguageState();

    /**
     * Adds a wantsLanguageState property value.<p>
     * 
     * @param newWantsLanguageState the wantsLanguageState property value to be added
     */
    void addWantsLanguageState(Object newWantsLanguageState);

    /**
     * Removes a wantsLanguageState property value.<p>
     * 
     * @param oldWantsLanguageState the wantsLanguageState property value to be removed.
     */
    void removeWantsLanguageState(Object oldWantsLanguageState);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
