package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: LanguageDetails <br>
 * @version generated on Fri May 23 10:57:54 CEST 2014 by cknguyen
 */

public interface LanguageDetails extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasLanguageName
     */
     
    /**
     * Gets all property values for the hasLanguageName property.<p>
     * 
     * @returns a collection of values for the hasLanguageName property.
     */
    Collection<? extends String> getHasLanguageName();

    /**
     * Checks if the class has a hasLanguageName property value.<p>
     * 
     * @return true if there is a hasLanguageName property value.
     */
    boolean hasHasLanguageName();

    /**
     * Adds a hasLanguageName property value.<p>
     * 
     * @param newHasLanguageName the hasLanguageName property value to be added
     */
    void addHasLanguageName(String newHasLanguageName);

    /**
     * Removes a hasLanguageName property value.<p>
     * 
     * @param oldHasLanguageName the hasLanguageName property value to be removed.
     */
    void removeHasLanguageName(String oldHasLanguageName);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
