package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: MappedLocation <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface MappedLocation extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationAerialway
     */
     
    /**
     * Gets all property values for the hasMappedLocationAerialway property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationAerialway property.
     */
    Collection<? extends String> getHasMappedLocationAerialway();

    /**
     * Checks if the class has a hasMappedLocationAerialway property value.<p>
     * 
     * @return true if there is a hasMappedLocationAerialway property value.
     */
    boolean hasHasMappedLocationAerialway();

    /**
     * Adds a hasMappedLocationAerialway property value.<p>
     * 
     * @param newHasMappedLocationAerialway the hasMappedLocationAerialway property value to be added
     */
    void addHasMappedLocationAerialway(String newHasMappedLocationAerialway);

    /**
     * Removes a hasMappedLocationAerialway property value.<p>
     * 
     * @param oldHasMappedLocationAerialway the hasMappedLocationAerialway property value to be removed.
     */
    void removeHasMappedLocationAerialway(String oldHasMappedLocationAerialway);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationDeviation
     */
     
    /**
     * Gets all property values for the hasMappedLocationDeviation property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationDeviation property.
     */
    Collection<? extends String> getHasMappedLocationDeviation();

    /**
     * Checks if the class has a hasMappedLocationDeviation property value.<p>
     * 
     * @return true if there is a hasMappedLocationDeviation property value.
     */
    boolean hasHasMappedLocationDeviation();

    /**
     * Adds a hasMappedLocationDeviation property value.<p>
     * 
     * @param newHasMappedLocationDeviation the hasMappedLocationDeviation property value to be added
     */
    void addHasMappedLocationDeviation(String newHasMappedLocationDeviation);

    /**
     * Removes a hasMappedLocationDeviation property value.<p>
     * 
     * @param oldHasMappedLocationDeviation the hasMappedLocationDeviation property value to be removed.
     */
    void removeHasMappedLocationDeviation(String oldHasMappedLocationDeviation);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationDistance
     */
     
    /**
     * Gets all property values for the hasMappedLocationDistance property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationDistance property.
     */
    Collection<? extends Object> getHasMappedLocationDistance();

    /**
     * Checks if the class has a hasMappedLocationDistance property value.<p>
     * 
     * @return true if there is a hasMappedLocationDistance property value.
     */
    boolean hasHasMappedLocationDistance();

    /**
     * Adds a hasMappedLocationDistance property value.<p>
     * 
     * @param newHasMappedLocationDistance the hasMappedLocationDistance property value to be added
     */
    void addHasMappedLocationDistance(Object newHasMappedLocationDistance);

    /**
     * Removes a hasMappedLocationDistance property value.<p>
     * 
     * @param oldHasMappedLocationDistance the hasMappedLocationDistance property value to be removed.
     */
    void removeHasMappedLocationDistance(Object oldHasMappedLocationDistance);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationHighway
     */
     
    /**
     * Gets all property values for the hasMappedLocationHighway property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationHighway property.
     */
    Collection<? extends String> getHasMappedLocationHighway();

    /**
     * Checks if the class has a hasMappedLocationHighway property value.<p>
     * 
     * @return true if there is a hasMappedLocationHighway property value.
     */
    boolean hasHasMappedLocationHighway();

    /**
     * Adds a hasMappedLocationHighway property value.<p>
     * 
     * @param newHasMappedLocationHighway the hasMappedLocationHighway property value to be added
     */
    void addHasMappedLocationHighway(String newHasMappedLocationHighway);

    /**
     * Removes a hasMappedLocationHighway property value.<p>
     * 
     * @param oldHasMappedLocationHighway the hasMappedLocationHighway property value to be removed.
     */
    void removeHasMappedLocationHighway(String oldHasMappedLocationHighway);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationID
     */
     
    /**
     * Gets all property values for the hasMappedLocationID property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationID property.
     */
    Collection<? extends Long> getHasMappedLocationID();

    /**
     * Checks if the class has a hasMappedLocationID property value.<p>
     * 
     * @return true if there is a hasMappedLocationID property value.
     */
    boolean hasHasMappedLocationID();

    /**
     * Adds a hasMappedLocationID property value.<p>
     * 
     * @param newHasMappedLocationID the hasMappedLocationID property value to be added
     */
    void addHasMappedLocationID(Long newHasMappedLocationID);

    /**
     * Removes a hasMappedLocationID property value.<p>
     * 
     * @param oldHasMappedLocationID the hasMappedLocationID property value to be removed.
     */
    void removeHasMappedLocationID(Long oldHasMappedLocationID);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationName
     */
     
    /**
     * Gets all property values for the hasMappedLocationName property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationName property.
     */
    Collection<? extends String> getHasMappedLocationName();

    /**
     * Checks if the class has a hasMappedLocationName property value.<p>
     * 
     * @return true if there is a hasMappedLocationName property value.
     */
    boolean hasHasMappedLocationName();

    /**
     * Adds a hasMappedLocationName property value.<p>
     * 
     * @param newHasMappedLocationName the hasMappedLocationName property value to be added
     */
    void addHasMappedLocationName(String newHasMappedLocationName);

    /**
     * Removes a hasMappedLocationName property value.<p>
     * 
     * @param oldHasMappedLocationName the hasMappedLocationName property value to be removed.
     */
    void removeHasMappedLocationName(String oldHasMappedLocationName);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationNodeID
     */
     
    /**
     * Gets all property values for the hasMappedLocationNodeID property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationNodeID property.
     */
    Collection<? extends Long> getHasMappedLocationNodeID();

    /**
     * Checks if the class has a hasMappedLocationNodeID property value.<p>
     * 
     * @return true if there is a hasMappedLocationNodeID property value.
     */
    boolean hasHasMappedLocationNodeID();

    /**
     * Adds a hasMappedLocationNodeID property value.<p>
     * 
     * @param newHasMappedLocationNodeID the hasMappedLocationNodeID property value to be added
     */
    void addHasMappedLocationNodeID(Long newHasMappedLocationNodeID);

    /**
     * Removes a hasMappedLocationNodeID property value.<p>
     * 
     * @param oldHasMappedLocationNodeID the hasMappedLocationNodeID property value to be removed.
     */
    void removeHasMappedLocationNodeID(Long oldHasMappedLocationNodeID);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationRailway
     */
     
    /**
     * Gets all property values for the hasMappedLocationRailway property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationRailway property.
     */
    Collection<? extends String> getHasMappedLocationRailway();

    /**
     * Checks if the class has a hasMappedLocationRailway property value.<p>
     * 
     * @return true if there is a hasMappedLocationRailway property value.
     */
    boolean hasHasMappedLocationRailway();

    /**
     * Adds a hasMappedLocationRailway property value.<p>
     * 
     * @param newHasMappedLocationRailway the hasMappedLocationRailway property value to be added
     */
    void addHasMappedLocationRailway(String newHasMappedLocationRailway);

    /**
     * Removes a hasMappedLocationRailway property value.<p>
     * 
     * @param oldHasMappedLocationRailway the hasMappedLocationRailway property value to be removed.
     */
    void removeHasMappedLocationRailway(String oldHasMappedLocationRailway);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationServiceRoadway
     */
     
    /**
     * Gets all property values for the hasMappedLocationServiceRoadway property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationServiceRoadway property.
     */
    Collection<? extends String> getHasMappedLocationServiceRoadway();

    /**
     * Checks if the class has a hasMappedLocationServiceRoadway property value.<p>
     * 
     * @return true if there is a hasMappedLocationServiceRoadway property value.
     */
    boolean hasHasMappedLocationServiceRoadway();

    /**
     * Adds a hasMappedLocationServiceRoadway property value.<p>
     * 
     * @param newHasMappedLocationServiceRoadway the hasMappedLocationServiceRoadway property value to be added
     */
    void addHasMappedLocationServiceRoadway(String newHasMappedLocationServiceRoadway);

    /**
     * Removes a hasMappedLocationServiceRoadway property value.<p>
     * 
     * @param oldHasMappedLocationServiceRoadway the hasMappedLocationServiceRoadway property value to be removed.
     */
    void removeHasMappedLocationServiceRoadway(String oldHasMappedLocationServiceRoadway);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationTime
     */
     
    /**
     * Gets all property values for the hasMappedLocationTime property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationTime property.
     */
    Collection<? extends Object> getHasMappedLocationTime();

    /**
     * Checks if the class has a hasMappedLocationTime property value.<p>
     * 
     * @return true if there is a hasMappedLocationTime property value.
     */
    boolean hasHasMappedLocationTime();

    /**
     * Adds a hasMappedLocationTime property value.<p>
     * 
     * @param newHasMappedLocationTime the hasMappedLocationTime property value to be added
     */
    void addHasMappedLocationTime(Object newHasMappedLocationTime);

    /**
     * Removes a hasMappedLocationTime property value.<p>
     * 
     * @param oldHasMappedLocationTime the hasMappedLocationTime property value to be removed.
     */
    void removeHasMappedLocationTime(Object oldHasMappedLocationTime);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationWaterway
     */
     
    /**
     * Gets all property values for the hasMappedLocationWaterway property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationWaterway property.
     */
    Collection<? extends String> getHasMappedLocationWaterway();

    /**
     * Checks if the class has a hasMappedLocationWaterway property value.<p>
     * 
     * @return true if there is a hasMappedLocationWaterway property value.
     */
    boolean hasHasMappedLocationWaterway();

    /**
     * Adds a hasMappedLocationWaterway property value.<p>
     * 
     * @param newHasMappedLocationWaterway the hasMappedLocationWaterway property value to be added
     */
    void addHasMappedLocationWaterway(String newHasMappedLocationWaterway);

    /**
     * Removes a hasMappedLocationWaterway property value.<p>
     * 
     * @param oldHasMappedLocationWaterway the hasMappedLocationWaterway property value to be removed.
     */
    void removeHasMappedLocationWaterway(String oldHasMappedLocationWaterway);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMappedLocationWayID
     */
     
    /**
     * Gets all property values for the hasMappedLocationWayID property.<p>
     * 
     * @returns a collection of values for the hasMappedLocationWayID property.
     */
    Collection<? extends Long> getHasMappedLocationWayID();

    /**
     * Checks if the class has a hasMappedLocationWayID property value.<p>
     * 
     * @return true if there is a hasMappedLocationWayID property value.
     */
    boolean hasHasMappedLocationWayID();

    /**
     * Adds a hasMappedLocationWayID property value.<p>
     * 
     * @param newHasMappedLocationWayID the hasMappedLocationWayID property value to be added
     */
    void addHasMappedLocationWayID(Long newHasMappedLocationWayID);

    /**
     * Removes a hasMappedLocationWayID property value.<p>
     * 
     * @param oldHasMappedLocationWayID the hasMappedLocationWayID property value to be removed.
     */
    void removeHasMappedLocationWayID(Long oldHasMappedLocationWayID);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#latitude
     */
     
    /**
     * Gets all property values for the latitude property.<p>
     * 
     * @returns a collection of values for the latitude property.
     */
    Collection<? extends Object> getLatitude();

    /**
     * Checks if the class has a latitude property value.<p>
     * 
     * @return true if there is a latitude property value.
     */
    boolean hasLatitude();

    /**
     * Adds a latitude property value.<p>
     * 
     * @param newLatitude the latitude property value to be added
     */
    void addLatitude(Object newLatitude);

    /**
     * Removes a latitude property value.<p>
     * 
     * @param oldLatitude the latitude property value to be removed.
     */
    void removeLatitude(Object oldLatitude);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#longitude
     */
     
    /**
     * Gets all property values for the longitude property.<p>
     * 
     * @returns a collection of values for the longitude property.
     */
    Collection<? extends Object> getLongitude();

    /**
     * Checks if the class has a longitude property value.<p>
     * 
     * @return true if there is a longitude property value.
     */
    boolean hasLongitude();

    /**
     * Adds a longitude property value.<p>
     * 
     * @param newLongitude the longitude property value to be added
     */
    void addLongitude(Object newLongitude);

    /**
     * Removes a longitude property value.<p>
     * 
     * @param oldLongitude the longitude property value to be removed.
     */
    void removeLongitude(Object oldLongitude);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
