package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PersonalPlace <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface PersonalPlace extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasDecisionLevel
     */
     
    /**
     * Gets all property values for the hasDecisionLevel property.<p>
     * 
     * @returns a collection of values for the hasDecisionLevel property.
     */
    Collection<? extends Object> getHasDecisionLevel();

    /**
     * Checks if the class has a hasDecisionLevel property value.<p>
     * 
     * @return true if there is a hasDecisionLevel property value.
     */
    boolean hasHasDecisionLevel();

    /**
     * Adds a hasDecisionLevel property value.<p>
     * 
     * @param newHasDecisionLevel the hasDecisionLevel property value to be added
     */
    void addHasDecisionLevel(Object newHasDecisionLevel);

    /**
     * Removes a hasDecisionLevel property value.<p>
     * 
     * @param oldHasDecisionLevel the hasDecisionLevel property value to be removed.
     */
    void removeHasDecisionLevel(Object oldHasDecisionLevel);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceAccuracy
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceAccuracy property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceAccuracy property.
     */
    Collection<? extends Object> getHasPersonalPlaceAccuracy();

    /**
     * Checks if the class has a hasPersonalPlaceAccuracy property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceAccuracy property value.
     */
    boolean hasHasPersonalPlaceAccuracy();

    /**
     * Adds a hasPersonalPlaceAccuracy property value.<p>
     * 
     * @param newHasPersonalPlaceAccuracy the hasPersonalPlaceAccuracy property value to be added
     */
    void addHasPersonalPlaceAccuracy(Object newHasPersonalPlaceAccuracy);

    /**
     * Removes a hasPersonalPlaceAccuracy property value.<p>
     * 
     * @param oldHasPersonalPlaceAccuracy the hasPersonalPlaceAccuracy property value to be removed.
     */
    void removeHasPersonalPlaceAccuracy(Object oldHasPersonalPlaceAccuracy);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceDayHourPattern
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceDayHourPattern property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceDayHourPattern property.
     */
    Collection<? extends String> getHasPersonalPlaceDayHourPattern();

    /**
     * Checks if the class has a hasPersonalPlaceDayHourPattern property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceDayHourPattern property value.
     */
    boolean hasHasPersonalPlaceDayHourPattern();

    /**
     * Adds a hasPersonalPlaceDayHourPattern property value.<p>
     * 
     * @param newHasPersonalPlaceDayHourPattern the hasPersonalPlaceDayHourPattern property value to be added
     */
    void addHasPersonalPlaceDayHourPattern(String newHasPersonalPlaceDayHourPattern);

    /**
     * Removes a hasPersonalPlaceDayHourPattern property value.<p>
     * 
     * @param oldHasPersonalPlaceDayHourPattern the hasPersonalPlaceDayHourPattern property value to be removed.
     */
    void removeHasPersonalPlaceDayHourPattern(String oldHasPersonalPlaceDayHourPattern);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceExternalIds
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceExternalIds property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceExternalIds property.
     */
    Collection<? extends String> getHasPersonalPlaceExternalIds();

    /**
     * Checks if the class has a hasPersonalPlaceExternalIds property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceExternalIds property value.
     */
    boolean hasHasPersonalPlaceExternalIds();

    /**
     * Adds a hasPersonalPlaceExternalIds property value.<p>
     * 
     * @param newHasPersonalPlaceExternalIds the hasPersonalPlaceExternalIds property value to be added
     */
    void addHasPersonalPlaceExternalIds(String newHasPersonalPlaceExternalIds);

    /**
     * Removes a hasPersonalPlaceExternalIds property value.<p>
     * 
     * @param oldHasPersonalPlaceExternalIds the hasPersonalPlaceExternalIds property value to be removed.
     */
    void removeHasPersonalPlaceExternalIds(String oldHasPersonalPlaceExternalIds);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceID
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceID property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceID property.
     */
    Collection<? extends Long> getHasPersonalPlaceID();

    /**
     * Checks if the class has a hasPersonalPlaceID property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceID property value.
     */
    boolean hasHasPersonalPlaceID();

    /**
     * Adds a hasPersonalPlaceID property value.<p>
     * 
     * @param newHasPersonalPlaceID the hasPersonalPlaceID property value to be added
     */
    void addHasPersonalPlaceID(Long newHasPersonalPlaceID);

    /**
     * Removes a hasPersonalPlaceID property value.<p>
     * 
     * @param oldHasPersonalPlaceID the hasPersonalPlaceID property value to be removed.
     */
    void removeHasPersonalPlaceID(Long oldHasPersonalPlaceID);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceName
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceName property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceName property.
     */
    Collection<? extends String> getHasPersonalPlaceName();

    /**
     * Checks if the class has a hasPersonalPlaceName property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceName property value.
     */
    boolean hasHasPersonalPlaceName();

    /**
     * Adds a hasPersonalPlaceName property value.<p>
     * 
     * @param newHasPersonalPlaceName the hasPersonalPlaceName property value to be added
     */
    void addHasPersonalPlaceName(String newHasPersonalPlaceName);

    /**
     * Removes a hasPersonalPlaceName property value.<p>
     * 
     * @param oldHasPersonalPlaceName the hasPersonalPlaceName property value to be removed.
     */
    void removeHasPersonalPlaceName(String oldHasPersonalPlaceName);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceStayDuration
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceStayDuration property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceStayDuration property.
     */
    Collection<? extends Long> getHasPersonalPlaceStayDuration();

    /**
     * Checks if the class has a hasPersonalPlaceStayDuration property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceStayDuration property value.
     */
    boolean hasHasPersonalPlaceStayDuration();

    /**
     * Adds a hasPersonalPlaceStayDuration property value.<p>
     * 
     * @param newHasPersonalPlaceStayDuration the hasPersonalPlaceStayDuration property value to be added
     */
    void addHasPersonalPlaceStayDuration(Long newHasPersonalPlaceStayDuration);

    /**
     * Removes a hasPersonalPlaceStayDuration property value.<p>
     * 
     * @param oldHasPersonalPlaceStayDuration the hasPersonalPlaceStayDuration property value to be removed.
     */
    void removeHasPersonalPlaceStayDuration(Long oldHasPersonalPlaceStayDuration);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceStayPercentage
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceStayPercentage property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceStayPercentage property.
     */
    Collection<? extends Object> getHasPersonalPlaceStayPercentage();

    /**
     * Checks if the class has a hasPersonalPlaceStayPercentage property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceStayPercentage property value.
     */
    boolean hasHasPersonalPlaceStayPercentage();

    /**
     * Adds a hasPersonalPlaceStayPercentage property value.<p>
     * 
     * @param newHasPersonalPlaceStayPercentage the hasPersonalPlaceStayPercentage property value to be added
     */
    void addHasPersonalPlaceStayPercentage(Object newHasPersonalPlaceStayPercentage);

    /**
     * Removes a hasPersonalPlaceStayPercentage property value.<p>
     * 
     * @param oldHasPersonalPlaceStayPercentage the hasPersonalPlaceStayPercentage property value to be removed.
     */
    void removeHasPersonalPlaceStayPercentage(Object oldHasPersonalPlaceStayPercentage);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceType
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceType property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceType property.
     */
    Collection<? extends String> getHasPersonalPlaceType();

    /**
     * Checks if the class has a hasPersonalPlaceType property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceType property value.
     */
    boolean hasHasPersonalPlaceType();

    /**
     * Adds a hasPersonalPlaceType property value.<p>
     * 
     * @param newHasPersonalPlaceType the hasPersonalPlaceType property value to be added
     */
    void addHasPersonalPlaceType(String newHasPersonalPlaceType);

    /**
     * Removes a hasPersonalPlaceType property value.<p>
     * 
     * @param oldHasPersonalPlaceType the hasPersonalPlaceType property value to be removed.
     */
    void removeHasPersonalPlaceType(String oldHasPersonalPlaceType);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPersonalPlaceWeekDayPattern
     */
     
    /**
     * Gets all property values for the hasPersonalPlaceWeekDayPattern property.<p>
     * 
     * @returns a collection of values for the hasPersonalPlaceWeekDayPattern property.
     */
    Collection<? extends String> getHasPersonalPlaceWeekDayPattern();

    /**
     * Checks if the class has a hasPersonalPlaceWeekDayPattern property value.<p>
     * 
     * @return true if there is a hasPersonalPlaceWeekDayPattern property value.
     */
    boolean hasHasPersonalPlaceWeekDayPattern();

    /**
     * Adds a hasPersonalPlaceWeekDayPattern property value.<p>
     * 
     * @param newHasPersonalPlaceWeekDayPattern the hasPersonalPlaceWeekDayPattern property value to be added
     */
    void addHasPersonalPlaceWeekDayPattern(String newHasPersonalPlaceWeekDayPattern);

    /**
     * Removes a hasPersonalPlaceWeekDayPattern property value.<p>
     * 
     * @param oldHasPersonalPlaceWeekDayPattern the hasPersonalPlaceWeekDayPattern property value to be removed.
     */
    void removeHasPersonalPlaceWeekDayPattern(String oldHasPersonalPlaceWeekDayPattern);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasUID
     */
     
    /**
     * Gets all property values for the hasUID property.<p>
     * 
     * @returns a collection of values for the hasUID property.
     */
    Collection<? extends String> getHasUID();

    /**
     * Checks if the class has a hasUID property value.<p>
     * 
     * @return true if there is a hasUID property value.
     */
    boolean hasHasUID();

    /**
     * Adds a hasUID property value.<p>
     * 
     * @param newHasUID the hasUID property value to be added
     */
    void addHasUID(String newHasUID);

    /**
     * Removes a hasUID property value.<p>
     * 
     * @param oldHasUID the hasUID property value to be removed.
     */
    void removeHasUID(String oldHasUID);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#latitude
     */
     
    /**
     * Gets all property values for the latitude property.<p>
     * 
     * @returns a collection of values for the latitude property.
     */
    Collection<? extends Object> getLatitude();

    /**
     * Checks if the class has a latitude property value.<p>
     * 
     * @return true if there is a latitude property value.
     */
    boolean hasLatitude();

    /**
     * Adds a latitude property value.<p>
     * 
     * @param newLatitude the latitude property value to be added
     */
    void addLatitude(Object newLatitude);

    /**
     * Removes a latitude property value.<p>
     * 
     * @param oldLatitude the latitude property value to be removed.
     */
    void removeLatitude(Object oldLatitude);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#longitude
     */
     
    /**
     * Gets all property values for the longitude property.<p>
     * 
     * @returns a collection of values for the longitude property.
     */
    Collection<? extends Object> getLongitude();

    /**
     * Checks if the class has a longitude property value.<p>
     * 
     * @return true if there is a longitude property value.
     */
    boolean hasLongitude();

    /**
     * Adds a longitude property value.<p>
     * 
     * @param newLongitude the longitude property value to be added
     */
    void addLongitude(Object newLongitude);

    /**
     * Removes a longitude property value.<p>
     * 
     * @param oldLongitude the longitude property value to be removed.
     */
    void removeLongitude(Object oldLongitude);



    /* ***************************************************
     * Property http://www.w3.org/2006/vcard/ns#postal-code
     */
     
    /**
     * Gets all property values for the postal_code property.<p>
     * 
     * @returns a collection of values for the postal_code property.
     */
    Collection<? extends Object> getPostal_code();

    /**
     * Checks if the class has a postal_code property value.<p>
     * 
     * @return true if there is a postal_code property value.
     */
    boolean hasPostal_code();

    /**
     * Adds a postal_code property value.<p>
     * 
     * @param newPostal_code the postal_code property value to be added
     */
    void addPostal_code(Object newPostal_code);

    /**
     * Removes a postal_code property value.<p>
     * 
     * @param oldPostal_code the postal_code property value to be removed.
     */
    void removePostal_code(Object oldPostal_code);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
