package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PlacePreference <br>
 * @version generated on Thu Jun 05 16:06:07 CEST 2014 by ragarwal
 */

public interface PlacePreference extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPlaceDetailPreference
     */
     
    /**
     * Gets all property values for the hasPlaceDetailPreference property.<p>
     * 
     * @returns a collection of values for the hasPlaceDetailPreference property.
     */
    Collection<? extends PlaceDetailPreference> getHasPlaceDetailPreference();

    /**
     * Checks if the class has a hasPlaceDetailPreference property value.<p>
     * 
     * @return true if there is a hasPlaceDetailPreference property value.
     */
    boolean hasHasPlaceDetailPreference();

    /**
     * Adds a hasPlaceDetailPreference property value.<p>
     * 
     * @param newHasPlaceDetailPreference the hasPlaceDetailPreference property value to be added
     */
    void addHasPlaceDetailPreference(PlaceDetailPreference newHasPlaceDetailPreference);

    /**
     * Removes a hasPlaceDetailPreference property value.<p>
     * 
     * @param oldHasPlaceDetailPreference the hasPlaceDetailPreference property value to be removed.
     */
    void removeHasPlaceDetailPreference(PlaceDetailPreference oldHasPlaceDetailPreference);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPlaceRatingPreference
     */
     
    /**
     * Gets all property values for the hasPlaceRatingPreference property.<p>
     * 
     * @returns a collection of values for the hasPlaceRatingPreference property.
     */
    Collection<? extends RatingPreference> getHasPlaceRatingPreference();

    /**
     * Checks if the class has a hasPlaceRatingPreference property value.<p>
     * 
     * @return true if there is a hasPlaceRatingPreference property value.
     */
    boolean hasHasPlaceRatingPreference();

    /**
     * Adds a hasPlaceRatingPreference property value.<p>
     * 
     * @param newHasPlaceRatingPreference the hasPlaceRatingPreference property value to be added
     */
    void addHasPlaceRatingPreference(RatingPreference newHasPlaceRatingPreference);

    /**
     * Removes a hasPlaceRatingPreference property value.<p>
     * 
     * @param oldHasPlaceRatingPreference the hasPlaceRatingPreference property value to be removed.
     */
    void removeHasPlaceRatingPreference(RatingPreference oldHasPlaceRatingPreference);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
