package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PlaceDetailPreference <br>
 * @version generated on Wed Jun 25 09:55:40 CEST 2014 by ragarwal
 */

public interface PlaceDetailPreference extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredApproximateAddress
     */
     
    /**
     * Gets all property values for the hasPreferredApproximateAddress property.<p>
     * 
     * @returns a collection of values for the hasPreferredApproximateAddress property.
     */
    Collection<? extends Address> getHasPreferredApproximateAddress();

    /**
     * Checks if the class has a hasPreferredApproximateAddress property value.<p>
     * 
     * @return true if there is a hasPreferredApproximateAddress property value.
     */
    boolean hasHasPreferredApproximateAddress();

    /**
     * Adds a hasPreferredApproximateAddress property value.<p>
     * 
     * @param newHasPreferredApproximateAddress the hasPreferredApproximateAddress property value to be added
     */
    void addHasPreferredApproximateAddress(Address newHasPreferredApproximateAddress);

    /**
     * Removes a hasPreferredApproximateAddress property value.<p>
     * 
     * @param oldHasPreferredApproximateAddress the hasPreferredApproximateAddress property value to be removed.
     */
    void removeHasPreferredApproximateAddress(Address oldHasPreferredApproximateAddress);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNatureOfPlace
     */
     
    /**
     * Gets all property values for the hasNatureOfPlace property.<p>
     * 
     * @returns a collection of values for the hasNatureOfPlace property.
     */
    Collection<? extends Object> getHasNatureOfPlace();

    /**
     * Checks if the class has a hasNatureOfPlace property value.<p>
     * 
     * @return true if there is a hasNatureOfPlace property value.
     */
    boolean hasHasNatureOfPlace();

    /**
     * Adds a hasNatureOfPlace property value.<p>
     * 
     * @param newHasNatureOfPlace the hasNatureOfPlace property value to be added
     */
    void addHasNatureOfPlace(Object newHasNatureOfPlace);

    /**
     * Removes a hasNatureOfPlace property value.<p>
     * 
     * @param oldHasNatureOfPlace the hasNatureOfPlace property value to be removed.
     */
    void removeHasNatureOfPlace(Object oldHasNatureOfPlace);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasPreferredPlaceKeyTags
     */
     
    /**
     * Gets all property values for the hasPreferredPlaceKeyTags property.<p>
     * 
     * @returns a collection of values for the hasPreferredPlaceKeyTags property.
     */
    Collection<? extends String> getHasPreferredPlaceKeyTags();

    /**
     * Checks if the class has a hasPreferredPlaceKeyTags property value.<p>
     * 
     * @return true if there is a hasPreferredPlaceKeyTags property value.
     */
    boolean hasHasPreferredPlaceKeyTags();

    /**
     * Adds a hasPreferredPlaceKeyTags property value.<p>
     * 
     * @param newHasPreferredPlaceKeyTags the hasPreferredPlaceKeyTags property value to be added
     */
    void addHasPreferredPlaceKeyTags(String newHasPreferredPlaceKeyTags);

    /**
     * Removes a hasPreferredPlaceKeyTags property value.<p>
     * 
     * @param oldHasPreferredPlaceKeyTags the hasPreferredPlaceKeyTags property value to be removed.
     */
    void removeHasPreferredPlaceKeyTags(String oldHasPreferredPlaceKeyTags);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
