package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: QueryHistory <br>
 * @version generated on Mon Jun 02 16:02:21 CEST 2014 by ragarwal
 */

public interface QueryHistory extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasQueryTime
     */
     
    /**
     * Gets all property values for the hasQueryTime property.<p>
     * 
     * @returns a collection of values for the hasQueryTime property.
     */
    Collection<? extends Object> getHasQueryTime();

    /**
     * Checks if the class has a hasQueryTime property value.<p>
     * 
     * @return true if there is a hasQueryTime property value.
     */
    boolean hasHasQueryTime();

    /**
     * Adds a hasQueryTime property value.<p>
     * 
     * @param newHasQueryTime the hasQueryTime property value to be added
     */
    void addHasQueryTime(Object newHasQueryTime);

    /**
     * Removes a hasQueryTime property value.<p>
     * 
     * @param oldHasQueryTime the hasQueryTime property value to be removed.
     */
    void removeHasQueryTime(Object oldHasQueryTime);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasUID
     */
     
    /**
     * Gets all property values for the hasUID property.<p>
     * 
     * @returns a collection of values for the hasUID property.
     */
    Collection<? extends String> getHasUID();

    /**
     * Checks if the class has a hasUID property value.<p>
     * 
     * @return true if there is a hasUID property value.
     */
    boolean hasHasUID();

    /**
     * Adds a hasUID property value.<p>
     * 
     * @param newHasUID the hasUID property value to be added
     */
    void addHasUID(String newHasUID);

    /**
     * Removes a hasUID property value.<p>
     * 
     * @param oldHasUID the hasUID property value to be removed.
     */
    void removeHasUID(String oldHasUID);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#query
     */
     
    /**
     * Gets all property values for the query property.<p>
     * 
     * @returns a collection of values for the query property.
     */
    Collection<? extends String> getQuery();

    /**
     * Checks if the class has a query property value.<p>
     * 
     * @return true if there is a query property value.
     */
    boolean hasQuery();

    /**
     * Adds a query property value.<p>
     * 
     * @param newQuery the query property value to be added
     */
    void addQuery(String newQuery);

    /**
     * Removes a query property value.<p>
     * 
     * @param oldQuery the query property value to be removed.
     */
    void removeQuery(String oldQuery);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
