package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Skill <br>
 * @version generated on Wed Jun 25 09:55:40 CEST 2014 by ragarwal
 */

public interface Skill extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasKeyTags
     */
     
    /**
     * Gets all property values for the hasKeyTags property.<p>
     * 
     * @returns a collection of values for the hasKeyTags property.
     */
    Collection<? extends String> getHasKeyTags();

    /**
     * Checks if the class has a hasKeyTags property value.<p>
     * 
     * @return true if there is a hasKeyTags property value.
     */
    boolean hasHasKeyTags();

    /**
     * Adds a hasKeyTags property value.<p>
     * 
     * @param newHasKeyTags the hasKeyTags property value to be added
     */
    void addHasKeyTags(String newHasKeyTags);

    /**
     * Removes a hasKeyTags property value.<p>
     * 
     * @param oldHasKeyTags the hasKeyTags property value to be removed.
     */
    void removeHasKeyTags(String oldHasKeyTags);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasMaturityLevel
     */
     
    /**
     * Gets all property values for the hasMaturityLevel property.<p>
     * 
     * @returns a collection of values for the hasMaturityLevel property.
     */
    Collection<? extends Object> getHasMaturityLevel();

    /**
     * Checks if the class has a hasMaturityLevel property value.<p>
     * 
     * @return true if there is a hasMaturityLevel property value.
     */
    boolean hasHasMaturityLevel();

    /**
     * Adds a hasMaturityLevel property value.<p>
     * 
     * @param newHasMaturityLevel the hasMaturityLevel property value to be added
     */
    void addHasMaturityLevel(Object newHasMaturityLevel);

    /**
     * Removes a hasMaturityLevel property value.<p>
     * 
     * @param oldHasMaturityLevel the hasMaturityLevel property value to be removed.
     */
    void removeHasMaturityLevel(Object oldHasMaturityLevel);



    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasSkillName
     */
     
    /**
     * Gets all property values for the hasSkillName property.<p>
     * 
     * @returns a collection of values for the hasSkillName property.
     */
    Collection<? extends String> getHasSkillName();

    /**
     * Checks if the class has a hasSkillName property value.<p>
     * 
     * @return true if there is a hasSkillName property value.
     */
    boolean hasHasSkillName();

    /**
     * Adds a hasSkillName property value.<p>
     * 
     * @param newHasSkillName the hasSkillName property value to be added
     */
    void addHasSkillName(String newHasSkillName);

    /**
     * Removes a hasSkillName property value.<p>
     * 
     * @param oldHasSkillName the hasSkillName property value to be removed.
     */
    void removeHasSkillName(String oldHasSkillName);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
