package eu.threecixty.models;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: UserEventRating <br>
 * @version generated on Mon Jun 02 16:02:21 CEST 2014 by ragarwal
 */

public interface UserEventRating extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasEventDetail
     */
     
    /**
     * Gets all property values for the hasEventDetail property.<p>
     * 
     * @returns a collection of values for the hasEventDetail property.
     */
    Collection<? extends EventDetails> getHasEventDetail();

    /**
     * Checks if the class has a hasEventDetail property value.<p>
     * 
     * @return true if there is a hasEventDetail property value.
     */
    boolean hasHasEventDetail();

    /**
     * Adds a hasEventDetail property value.<p>
     * 
     * @param newHasEventDetail the hasEventDetail property value to be added
     */
    void addHasEventDetail(EventDetails newHasEventDetail);

    /**
     * Removes a hasEventDetail property value.<p>
     * 
     * @param oldHasEventDetail the hasEventDetail property value to be removed.
     */
    void removeHasEventDetail(EventDetails oldHasEventDetail);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasRating
     */
     
    /**
     * Gets all property values for the hasRating property.<p>
     * 
     * @returns a collection of values for the hasRating property.
     */
    Collection<? extends Rating> getHasRating();

    /**
     * Checks if the class has a hasRating property value.<p>
     * 
     * @return true if there is a hasRating property value.
     */
    boolean hasHasRating();

    /**
     * Adds a hasRating property value.<p>
     * 
     * @param newHasRating the hasRating property value to be added
     */
    void addHasRating(Rating newHasRating);

    /**
     * Removes a hasRating property value.<p>
     * 
     * @param oldHasRating the hasRating property value to be removed.
     */
    void removeHasRating(Rating oldHasRating);


    /* ***************************************************
     * Property http://www.eu.3cixty.org/profile#hasNumberofTimesVisited
     */
     
    /**
     * Gets all property values for the hasNumberofTimesVisited property.<p>
     * 
     * @returns a collection of values for the hasNumberofTimesVisited property.
     */
    Collection<? extends Integer> getHasNumberofTimesVisited();

    /**
     * Checks if the class has a hasNumberofTimesVisited property value.<p>
     * 
     * @return true if there is a hasNumberofTimesVisited property value.
     */
    boolean hasHasNumberofTimesVisited();

    /**
     * Adds a hasNumberofTimesVisited property value.<p>
     * 
     * @param newHasNumberofTimesVisited the hasNumberofTimesVisited property value to be added
     */
    void addHasNumberofTimesVisited(Integer newHasNumberofTimesVisited);

    /**
     * Removes a hasNumberofTimesVisited property value.<p>
     * 
     * @param oldHasNumberofTimesVisited the hasNumberofTimesVisited property value to be removed.
     */
    void removeHasNumberofTimesVisited(Integer oldHasNumberofTimesVisited);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
